-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gemm_int8_gemm_int8_Pipeline_init_acc_VITIS_LOOP_46_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_ce0 : OUT STD_LOGIC;
    acc_we0 : OUT STD_LOGIC;
    acc_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_31_ce0 : OUT STD_LOGIC;
    acc_31_we0 : OUT STD_LOGIC;
    acc_31_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_30_ce0 : OUT STD_LOGIC;
    acc_30_we0 : OUT STD_LOGIC;
    acc_30_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_29_ce0 : OUT STD_LOGIC;
    acc_29_we0 : OUT STD_LOGIC;
    acc_29_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_28_ce0 : OUT STD_LOGIC;
    acc_28_we0 : OUT STD_LOGIC;
    acc_28_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_27_ce0 : OUT STD_LOGIC;
    acc_27_we0 : OUT STD_LOGIC;
    acc_27_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_26_ce0 : OUT STD_LOGIC;
    acc_26_we0 : OUT STD_LOGIC;
    acc_26_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_25_ce0 : OUT STD_LOGIC;
    acc_25_we0 : OUT STD_LOGIC;
    acc_25_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_24_ce0 : OUT STD_LOGIC;
    acc_24_we0 : OUT STD_LOGIC;
    acc_24_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_23_ce0 : OUT STD_LOGIC;
    acc_23_we0 : OUT STD_LOGIC;
    acc_23_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_22_ce0 : OUT STD_LOGIC;
    acc_22_we0 : OUT STD_LOGIC;
    acc_22_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_21_ce0 : OUT STD_LOGIC;
    acc_21_we0 : OUT STD_LOGIC;
    acc_21_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_20_ce0 : OUT STD_LOGIC;
    acc_20_we0 : OUT STD_LOGIC;
    acc_20_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_19_ce0 : OUT STD_LOGIC;
    acc_19_we0 : OUT STD_LOGIC;
    acc_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_18_ce0 : OUT STD_LOGIC;
    acc_18_we0 : OUT STD_LOGIC;
    acc_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_17_ce0 : OUT STD_LOGIC;
    acc_17_we0 : OUT STD_LOGIC;
    acc_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_16_ce0 : OUT STD_LOGIC;
    acc_16_we0 : OUT STD_LOGIC;
    acc_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_15_ce0 : OUT STD_LOGIC;
    acc_15_we0 : OUT STD_LOGIC;
    acc_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_14_ce0 : OUT STD_LOGIC;
    acc_14_we0 : OUT STD_LOGIC;
    acc_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_13_ce0 : OUT STD_LOGIC;
    acc_13_we0 : OUT STD_LOGIC;
    acc_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_12_ce0 : OUT STD_LOGIC;
    acc_12_we0 : OUT STD_LOGIC;
    acc_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_11_ce0 : OUT STD_LOGIC;
    acc_11_we0 : OUT STD_LOGIC;
    acc_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_10_ce0 : OUT STD_LOGIC;
    acc_10_we0 : OUT STD_LOGIC;
    acc_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_9_ce0 : OUT STD_LOGIC;
    acc_9_we0 : OUT STD_LOGIC;
    acc_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_8_ce0 : OUT STD_LOGIC;
    acc_8_we0 : OUT STD_LOGIC;
    acc_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_7_ce0 : OUT STD_LOGIC;
    acc_7_we0 : OUT STD_LOGIC;
    acc_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_6_ce0 : OUT STD_LOGIC;
    acc_6_we0 : OUT STD_LOGIC;
    acc_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_5_ce0 : OUT STD_LOGIC;
    acc_5_we0 : OUT STD_LOGIC;
    acc_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_4_ce0 : OUT STD_LOGIC;
    acc_4_we0 : OUT STD_LOGIC;
    acc_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_3_ce0 : OUT STD_LOGIC;
    acc_3_we0 : OUT STD_LOGIC;
    acc_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_2_ce0 : OUT STD_LOGIC;
    acc_2_we0 : OUT STD_LOGIC;
    acc_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    acc_1_ce0 : OUT STD_LOGIC;
    acc_1_we0 : OUT STD_LOGIC;
    acc_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of gemm_int8_gemm_int8_Pipeline_init_acc_VITIS_LOOP_46_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln45_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln45_fu_682_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln46_fu_718_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_fu_158 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln46_fu_722_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (5 downto 0);
    signal i_fu_162 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln45_1_fu_674_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten38_fu_166 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln45_1_fu_642_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten38_load : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln46_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln45_fu_654_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln45_fu_666_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gemm_int8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gemm_int8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln45_fu_636_p2 = ap_const_lv1_0)) then 
                    i_fu_162 <= select_ln45_1_fu_674_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_162 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten38_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln45_fu_636_p2 = ap_const_lv1_0)) then 
                    indvar_flatten38_fu_166 <= add_ln45_1_fu_642_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten38_fu_166 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln45_fu_636_p2 = ap_const_lv1_0)) then 
                    j_fu_158 <= add_ln46_fu_722_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_158 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_10_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_10_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_10_ce0 <= ap_const_logic_1;
        else 
            acc_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_10_d0 <= ap_const_lv32_0;

    acc_10_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_A) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_10_we0 <= ap_const_logic_1;
        else 
            acc_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_11_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_11_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_11_ce0 <= ap_const_logic_1;
        else 
            acc_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_11_d0 <= ap_const_lv32_0;

    acc_11_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_B) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_11_we0 <= ap_const_logic_1;
        else 
            acc_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_12_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_12_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_12_ce0 <= ap_const_logic_1;
        else 
            acc_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_12_d0 <= ap_const_lv32_0;

    acc_12_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_C) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_12_we0 <= ap_const_logic_1;
        else 
            acc_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_13_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_13_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_13_ce0 <= ap_const_logic_1;
        else 
            acc_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_13_d0 <= ap_const_lv32_0;

    acc_13_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_D) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_13_we0 <= ap_const_logic_1;
        else 
            acc_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_14_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_14_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_14_ce0 <= ap_const_logic_1;
        else 
            acc_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_14_d0 <= ap_const_lv32_0;

    acc_14_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_E) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_14_we0 <= ap_const_logic_1;
        else 
            acc_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_15_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_15_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_15_ce0 <= ap_const_logic_1;
        else 
            acc_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_15_d0 <= ap_const_lv32_0;

    acc_15_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_F) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_15_we0 <= ap_const_logic_1;
        else 
            acc_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_16_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_16_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_16_ce0 <= ap_const_logic_1;
        else 
            acc_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_16_d0 <= ap_const_lv32_0;

    acc_16_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_10) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_16_we0 <= ap_const_logic_1;
        else 
            acc_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_17_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_17_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_17_ce0 <= ap_const_logic_1;
        else 
            acc_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_17_d0 <= ap_const_lv32_0;

    acc_17_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_11) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_17_we0 <= ap_const_logic_1;
        else 
            acc_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_18_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_18_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_18_ce0 <= ap_const_logic_1;
        else 
            acc_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_18_d0 <= ap_const_lv32_0;

    acc_18_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_12) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_18_we0 <= ap_const_logic_1;
        else 
            acc_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_19_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_19_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_19_ce0 <= ap_const_logic_1;
        else 
            acc_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_19_d0 <= ap_const_lv32_0;

    acc_19_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_13) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_19_we0 <= ap_const_logic_1;
        else 
            acc_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_1_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_1_ce0 <= ap_const_logic_1;
        else 
            acc_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_d0 <= ap_const_lv32_0;

    acc_1_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_1_we0 <= ap_const_logic_1;
        else 
            acc_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_20_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_20_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_20_ce0 <= ap_const_logic_1;
        else 
            acc_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_20_d0 <= ap_const_lv32_0;

    acc_20_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_14) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_20_we0 <= ap_const_logic_1;
        else 
            acc_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_21_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_21_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_21_ce0 <= ap_const_logic_1;
        else 
            acc_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_21_d0 <= ap_const_lv32_0;

    acc_21_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_15) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_21_we0 <= ap_const_logic_1;
        else 
            acc_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_22_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_22_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_22_ce0 <= ap_const_logic_1;
        else 
            acc_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_22_d0 <= ap_const_lv32_0;

    acc_22_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_16) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_22_we0 <= ap_const_logic_1;
        else 
            acc_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_23_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_23_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_23_ce0 <= ap_const_logic_1;
        else 
            acc_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_23_d0 <= ap_const_lv32_0;

    acc_23_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_17) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_23_we0 <= ap_const_logic_1;
        else 
            acc_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_24_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_24_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_24_ce0 <= ap_const_logic_1;
        else 
            acc_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_24_d0 <= ap_const_lv32_0;

    acc_24_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_18) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_24_we0 <= ap_const_logic_1;
        else 
            acc_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_25_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_25_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_25_ce0 <= ap_const_logic_1;
        else 
            acc_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_25_d0 <= ap_const_lv32_0;

    acc_25_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_19) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_25_we0 <= ap_const_logic_1;
        else 
            acc_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_26_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_26_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_26_ce0 <= ap_const_logic_1;
        else 
            acc_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_26_d0 <= ap_const_lv32_0;

    acc_26_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1A) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_26_we0 <= ap_const_logic_1;
        else 
            acc_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_27_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_27_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_27_ce0 <= ap_const_logic_1;
        else 
            acc_27_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_27_d0 <= ap_const_lv32_0;

    acc_27_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1B) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_27_we0 <= ap_const_logic_1;
        else 
            acc_27_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_28_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_28_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_28_ce0 <= ap_const_logic_1;
        else 
            acc_28_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_28_d0 <= ap_const_lv32_0;

    acc_28_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1C) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_28_we0 <= ap_const_logic_1;
        else 
            acc_28_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_29_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_29_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_29_ce0 <= ap_const_logic_1;
        else 
            acc_29_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_29_d0 <= ap_const_lv32_0;

    acc_29_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1D) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_29_we0 <= ap_const_logic_1;
        else 
            acc_29_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_2_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_2_ce0 <= ap_const_logic_1;
        else 
            acc_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_d0 <= ap_const_lv32_0;

    acc_2_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_2) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_2_we0 <= ap_const_logic_1;
        else 
            acc_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_30_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_30_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_30_ce0 <= ap_const_logic_1;
        else 
            acc_30_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_30_d0 <= ap_const_lv32_0;

    acc_30_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1E) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_30_we0 <= ap_const_logic_1;
        else 
            acc_30_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_31_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_31_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_31_ce0 <= ap_const_logic_1;
        else 
            acc_31_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_31_d0 <= ap_const_lv32_0;

    acc_31_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_1F) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_31_we0 <= ap_const_logic_1;
        else 
            acc_31_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_3_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_3_ce0 <= ap_const_logic_1;
        else 
            acc_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_d0 <= ap_const_lv32_0;

    acc_3_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_3) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_3_we0 <= ap_const_logic_1;
        else 
            acc_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_4_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_4_ce0 <= ap_const_logic_1;
        else 
            acc_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_d0 <= ap_const_lv32_0;

    acc_4_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_4) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_4_we0 <= ap_const_logic_1;
        else 
            acc_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_5_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_5_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_5_ce0 <= ap_const_logic_1;
        else 
            acc_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_5_d0 <= ap_const_lv32_0;

    acc_5_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_5) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_5_we0 <= ap_const_logic_1;
        else 
            acc_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_6_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_6_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_6_ce0 <= ap_const_logic_1;
        else 
            acc_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_6_d0 <= ap_const_lv32_0;

    acc_6_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_6) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_6_we0 <= ap_const_logic_1;
        else 
            acc_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_7_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_7_ce0 <= ap_const_logic_1;
        else 
            acc_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_d0 <= ap_const_lv32_0;

    acc_7_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_7) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_7_we0 <= ap_const_logic_1;
        else 
            acc_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_8_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_8_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_8_ce0 <= ap_const_logic_1;
        else 
            acc_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_8_d0 <= ap_const_lv32_0;

    acc_8_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_8) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_8_we0 <= ap_const_logic_1;
        else 
            acc_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_9_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_9_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_9_ce0 <= ap_const_logic_1;
        else 
            acc_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_9_d0 <= ap_const_lv32_0;

    acc_9_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_9) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_9_we0 <= ap_const_logic_1;
        else 
            acc_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_address0 <= zext_ln45_fu_682_p1(5 - 1 downto 0);

    acc_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_ce0 <= ap_const_logic_1;
        else 
            acc_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_d0 <= ap_const_lv32_0;

    acc_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, trunc_ln46_fu_718_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (trunc_ln46_fu_718_p1 = ap_const_lv5_0) and (icmp_ln45_fu_636_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_we0 <= ap_const_logic_1;
        else 
            acc_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln45_1_fu_642_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten38_load) + unsigned(ap_const_lv11_1));
    add_ln45_fu_654_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv6_1));
    add_ln46_fu_722_p2 <= std_logic_vector(unsigned(select_ln45_fu_666_p3) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln45_fu_636_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln45_fu_636_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, i_fu_162)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_162;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten38_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten38_fu_166)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_indvar_flatten38_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten38_load <= indvar_flatten38_fu_166;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_state1, j_fu_158, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_158;
        end if; 
    end process;

    icmp_ln45_fu_636_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten38_load = ap_const_lv11_400) else "0";
    icmp_ln46_fu_660_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv6_20) else "0";
    select_ln45_1_fu_674_p3 <= 
        add_ln45_fu_654_p2 when (icmp_ln46_fu_660_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln45_fu_666_p3 <= 
        ap_const_lv6_0 when (icmp_ln46_fu_660_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    trunc_ln46_fu_718_p1 <= select_ln45_fu_666_p3(5 - 1 downto 0);
    zext_ln45_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_1_fu_674_p3),64));
end behav;
