// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_int8_gemm_int8_Pipeline_init_acc_VITIS_LOOP_46_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_address0,
        acc_ce0,
        acc_we0,
        acc_d0,
        acc_31_address0,
        acc_31_ce0,
        acc_31_we0,
        acc_31_d0,
        acc_30_address0,
        acc_30_ce0,
        acc_30_we0,
        acc_30_d0,
        acc_29_address0,
        acc_29_ce0,
        acc_29_we0,
        acc_29_d0,
        acc_28_address0,
        acc_28_ce0,
        acc_28_we0,
        acc_28_d0,
        acc_27_address0,
        acc_27_ce0,
        acc_27_we0,
        acc_27_d0,
        acc_26_address0,
        acc_26_ce0,
        acc_26_we0,
        acc_26_d0,
        acc_25_address0,
        acc_25_ce0,
        acc_25_we0,
        acc_25_d0,
        acc_24_address0,
        acc_24_ce0,
        acc_24_we0,
        acc_24_d0,
        acc_23_address0,
        acc_23_ce0,
        acc_23_we0,
        acc_23_d0,
        acc_22_address0,
        acc_22_ce0,
        acc_22_we0,
        acc_22_d0,
        acc_21_address0,
        acc_21_ce0,
        acc_21_we0,
        acc_21_d0,
        acc_20_address0,
        acc_20_ce0,
        acc_20_we0,
        acc_20_d0,
        acc_19_address0,
        acc_19_ce0,
        acc_19_we0,
        acc_19_d0,
        acc_18_address0,
        acc_18_ce0,
        acc_18_we0,
        acc_18_d0,
        acc_17_address0,
        acc_17_ce0,
        acc_17_we0,
        acc_17_d0,
        acc_16_address0,
        acc_16_ce0,
        acc_16_we0,
        acc_16_d0,
        acc_15_address0,
        acc_15_ce0,
        acc_15_we0,
        acc_15_d0,
        acc_14_address0,
        acc_14_ce0,
        acc_14_we0,
        acc_14_d0,
        acc_13_address0,
        acc_13_ce0,
        acc_13_we0,
        acc_13_d0,
        acc_12_address0,
        acc_12_ce0,
        acc_12_we0,
        acc_12_d0,
        acc_11_address0,
        acc_11_ce0,
        acc_11_we0,
        acc_11_d0,
        acc_10_address0,
        acc_10_ce0,
        acc_10_we0,
        acc_10_d0,
        acc_9_address0,
        acc_9_ce0,
        acc_9_we0,
        acc_9_d0,
        acc_8_address0,
        acc_8_ce0,
        acc_8_we0,
        acc_8_d0,
        acc_7_address0,
        acc_7_ce0,
        acc_7_we0,
        acc_7_d0,
        acc_6_address0,
        acc_6_ce0,
        acc_6_we0,
        acc_6_d0,
        acc_5_address0,
        acc_5_ce0,
        acc_5_we0,
        acc_5_d0,
        acc_4_address0,
        acc_4_ce0,
        acc_4_we0,
        acc_4_d0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_we0,
        acc_3_d0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_we0,
        acc_2_d0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_we0,
        acc_1_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] acc_address0;
output   acc_ce0;
output   acc_we0;
output  [31:0] acc_d0;
output  [4:0] acc_31_address0;
output   acc_31_ce0;
output   acc_31_we0;
output  [31:0] acc_31_d0;
output  [4:0] acc_30_address0;
output   acc_30_ce0;
output   acc_30_we0;
output  [31:0] acc_30_d0;
output  [4:0] acc_29_address0;
output   acc_29_ce0;
output   acc_29_we0;
output  [31:0] acc_29_d0;
output  [4:0] acc_28_address0;
output   acc_28_ce0;
output   acc_28_we0;
output  [31:0] acc_28_d0;
output  [4:0] acc_27_address0;
output   acc_27_ce0;
output   acc_27_we0;
output  [31:0] acc_27_d0;
output  [4:0] acc_26_address0;
output   acc_26_ce0;
output   acc_26_we0;
output  [31:0] acc_26_d0;
output  [4:0] acc_25_address0;
output   acc_25_ce0;
output   acc_25_we0;
output  [31:0] acc_25_d0;
output  [4:0] acc_24_address0;
output   acc_24_ce0;
output   acc_24_we0;
output  [31:0] acc_24_d0;
output  [4:0] acc_23_address0;
output   acc_23_ce0;
output   acc_23_we0;
output  [31:0] acc_23_d0;
output  [4:0] acc_22_address0;
output   acc_22_ce0;
output   acc_22_we0;
output  [31:0] acc_22_d0;
output  [4:0] acc_21_address0;
output   acc_21_ce0;
output   acc_21_we0;
output  [31:0] acc_21_d0;
output  [4:0] acc_20_address0;
output   acc_20_ce0;
output   acc_20_we0;
output  [31:0] acc_20_d0;
output  [4:0] acc_19_address0;
output   acc_19_ce0;
output   acc_19_we0;
output  [31:0] acc_19_d0;
output  [4:0] acc_18_address0;
output   acc_18_ce0;
output   acc_18_we0;
output  [31:0] acc_18_d0;
output  [4:0] acc_17_address0;
output   acc_17_ce0;
output   acc_17_we0;
output  [31:0] acc_17_d0;
output  [4:0] acc_16_address0;
output   acc_16_ce0;
output   acc_16_we0;
output  [31:0] acc_16_d0;
output  [4:0] acc_15_address0;
output   acc_15_ce0;
output   acc_15_we0;
output  [31:0] acc_15_d0;
output  [4:0] acc_14_address0;
output   acc_14_ce0;
output   acc_14_we0;
output  [31:0] acc_14_d0;
output  [4:0] acc_13_address0;
output   acc_13_ce0;
output   acc_13_we0;
output  [31:0] acc_13_d0;
output  [4:0] acc_12_address0;
output   acc_12_ce0;
output   acc_12_we0;
output  [31:0] acc_12_d0;
output  [4:0] acc_11_address0;
output   acc_11_ce0;
output   acc_11_we0;
output  [31:0] acc_11_d0;
output  [4:0] acc_10_address0;
output   acc_10_ce0;
output   acc_10_we0;
output  [31:0] acc_10_d0;
output  [4:0] acc_9_address0;
output   acc_9_ce0;
output   acc_9_we0;
output  [31:0] acc_9_d0;
output  [4:0] acc_8_address0;
output   acc_8_ce0;
output   acc_8_we0;
output  [31:0] acc_8_d0;
output  [4:0] acc_7_address0;
output   acc_7_ce0;
output   acc_7_we0;
output  [31:0] acc_7_d0;
output  [4:0] acc_6_address0;
output   acc_6_ce0;
output   acc_6_we0;
output  [31:0] acc_6_d0;
output  [4:0] acc_5_address0;
output   acc_5_ce0;
output   acc_5_we0;
output  [31:0] acc_5_d0;
output  [4:0] acc_4_address0;
output   acc_4_ce0;
output   acc_4_we0;
output  [31:0] acc_4_d0;
output  [4:0] acc_3_address0;
output   acc_3_ce0;
output   acc_3_we0;
output  [31:0] acc_3_d0;
output  [4:0] acc_2_address0;
output   acc_2_ce0;
output   acc_2_we0;
output  [31:0] acc_2_d0;
output  [4:0] acc_1_address0;
output   acc_1_ce0;
output   acc_1_we0;
output  [31:0] acc_1_d0;

reg ap_idle;
reg acc_ce0;
reg acc_we0;
reg acc_31_ce0;
reg acc_31_we0;
reg acc_30_ce0;
reg acc_30_we0;
reg acc_29_ce0;
reg acc_29_we0;
reg acc_28_ce0;
reg acc_28_we0;
reg acc_27_ce0;
reg acc_27_we0;
reg acc_26_ce0;
reg acc_26_we0;
reg acc_25_ce0;
reg acc_25_we0;
reg acc_24_ce0;
reg acc_24_we0;
reg acc_23_ce0;
reg acc_23_we0;
reg acc_22_ce0;
reg acc_22_we0;
reg acc_21_ce0;
reg acc_21_we0;
reg acc_20_ce0;
reg acc_20_we0;
reg acc_19_ce0;
reg acc_19_we0;
reg acc_18_ce0;
reg acc_18_we0;
reg acc_17_ce0;
reg acc_17_we0;
reg acc_16_ce0;
reg acc_16_we0;
reg acc_15_ce0;
reg acc_15_we0;
reg acc_14_ce0;
reg acc_14_we0;
reg acc_13_ce0;
reg acc_13_we0;
reg acc_12_ce0;
reg acc_12_we0;
reg acc_11_ce0;
reg acc_11_we0;
reg acc_10_ce0;
reg acc_10_we0;
reg acc_9_ce0;
reg acc_9_we0;
reg acc_8_ce0;
reg acc_8_we0;
reg acc_7_ce0;
reg acc_7_we0;
reg acc_6_ce0;
reg acc_6_we0;
reg acc_5_ce0;
reg acc_5_we0;
reg acc_4_ce0;
reg acc_4_we0;
reg acc_3_ce0;
reg acc_3_we0;
reg acc_2_ce0;
reg acc_2_we0;
reg acc_1_ce0;
reg acc_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln45_fu_636_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln45_fu_682_p1;
wire   [4:0] trunc_ln46_fu_718_p1;
reg   [5:0] j_fu_158;
wire   [5:0] add_ln46_fu_722_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_load;
reg   [5:0] i_fu_162;
wire   [5:0] select_ln45_1_fu_674_p3;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [10:0] indvar_flatten38_fu_166;
wire   [10:0] add_ln45_1_fu_642_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten38_load;
wire   [0:0] icmp_ln46_fu_660_p2;
wire   [5:0] add_ln45_fu_654_p2;
wire   [5:0] select_ln45_fu_666_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

gemm_int8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln45_fu_636_p2 == 1'd0)) begin
            i_fu_162 <= select_ln45_1_fu_674_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_162 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln45_fu_636_p2 == 1'd0)) begin
            indvar_flatten38_fu_166 <= add_ln45_1_fu_642_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten38_fu_166 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln45_fu_636_p2 == 1'd0)) begin
            j_fu_158 <= add_ln46_fu_722_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_158 <= 6'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_10_ce0 = 1'b1;
    end else begin
        acc_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd10) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_10_we0 = 1'b1;
    end else begin
        acc_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_11_ce0 = 1'b1;
    end else begin
        acc_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd11) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_11_we0 = 1'b1;
    end else begin
        acc_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_12_ce0 = 1'b1;
    end else begin
        acc_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd12) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_12_we0 = 1'b1;
    end else begin
        acc_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_13_ce0 = 1'b1;
    end else begin
        acc_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd13) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_13_we0 = 1'b1;
    end else begin
        acc_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_14_ce0 = 1'b1;
    end else begin
        acc_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd14) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_14_we0 = 1'b1;
    end else begin
        acc_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_15_ce0 = 1'b1;
    end else begin
        acc_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd15) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_15_we0 = 1'b1;
    end else begin
        acc_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_16_ce0 = 1'b1;
    end else begin
        acc_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd16) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_16_we0 = 1'b1;
    end else begin
        acc_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_17_ce0 = 1'b1;
    end else begin
        acc_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd17) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_17_we0 = 1'b1;
    end else begin
        acc_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_18_ce0 = 1'b1;
    end else begin
        acc_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd18) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_18_we0 = 1'b1;
    end else begin
        acc_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_19_ce0 = 1'b1;
    end else begin
        acc_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd19) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_19_we0 = 1'b1;
    end else begin
        acc_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_ce0 = 1'b1;
    end else begin
        acc_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd1) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_we0 = 1'b1;
    end else begin
        acc_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_20_ce0 = 1'b1;
    end else begin
        acc_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd20) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_20_we0 = 1'b1;
    end else begin
        acc_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_21_ce0 = 1'b1;
    end else begin
        acc_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd21) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_21_we0 = 1'b1;
    end else begin
        acc_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_22_ce0 = 1'b1;
    end else begin
        acc_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd22) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_22_we0 = 1'b1;
    end else begin
        acc_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_23_ce0 = 1'b1;
    end else begin
        acc_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd23) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_23_we0 = 1'b1;
    end else begin
        acc_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_24_ce0 = 1'b1;
    end else begin
        acc_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd24) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_24_we0 = 1'b1;
    end else begin
        acc_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_25_ce0 = 1'b1;
    end else begin
        acc_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd25) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_25_we0 = 1'b1;
    end else begin
        acc_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_26_ce0 = 1'b1;
    end else begin
        acc_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd26) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_26_we0 = 1'b1;
    end else begin
        acc_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_27_ce0 = 1'b1;
    end else begin
        acc_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd27) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_27_we0 = 1'b1;
    end else begin
        acc_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_28_ce0 = 1'b1;
    end else begin
        acc_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd28) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_28_we0 = 1'b1;
    end else begin
        acc_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_29_ce0 = 1'b1;
    end else begin
        acc_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd29) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_29_we0 = 1'b1;
    end else begin
        acc_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_ce0 = 1'b1;
    end else begin
        acc_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd2) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_we0 = 1'b1;
    end else begin
        acc_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_30_ce0 = 1'b1;
    end else begin
        acc_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd30) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_30_we0 = 1'b1;
    end else begin
        acc_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_31_ce0 = 1'b1;
    end else begin
        acc_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd31) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_31_we0 = 1'b1;
    end else begin
        acc_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_ce0 = 1'b1;
    end else begin
        acc_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd3) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_we0 = 1'b1;
    end else begin
        acc_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_ce0 = 1'b1;
    end else begin
        acc_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd4) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_we0 = 1'b1;
    end else begin
        acc_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_ce0 = 1'b1;
    end else begin
        acc_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd5) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_we0 = 1'b1;
    end else begin
        acc_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_ce0 = 1'b1;
    end else begin
        acc_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd6) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_we0 = 1'b1;
    end else begin
        acc_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_ce0 = 1'b1;
    end else begin
        acc_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd7) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_we0 = 1'b1;
    end else begin
        acc_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_8_ce0 = 1'b1;
    end else begin
        acc_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd8) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_8_we0 = 1'b1;
    end else begin
        acc_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_9_ce0 = 1'b1;
    end else begin
        acc_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd9) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_9_we0 = 1'b1;
    end else begin
        acc_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_ce0 = 1'b1;
    end else begin
        acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln46_fu_718_p1 == 5'd0) & (icmp_ln45_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_we0 = 1'b1;
    end else begin
        acc_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln45_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_162;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten38_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten38_load = indvar_flatten38_fu_166;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_load = 6'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_158;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_address0 = zext_ln45_fu_682_p1;

assign acc_10_d0 = 32'd0;

assign acc_11_address0 = zext_ln45_fu_682_p1;

assign acc_11_d0 = 32'd0;

assign acc_12_address0 = zext_ln45_fu_682_p1;

assign acc_12_d0 = 32'd0;

assign acc_13_address0 = zext_ln45_fu_682_p1;

assign acc_13_d0 = 32'd0;

assign acc_14_address0 = zext_ln45_fu_682_p1;

assign acc_14_d0 = 32'd0;

assign acc_15_address0 = zext_ln45_fu_682_p1;

assign acc_15_d0 = 32'd0;

assign acc_16_address0 = zext_ln45_fu_682_p1;

assign acc_16_d0 = 32'd0;

assign acc_17_address0 = zext_ln45_fu_682_p1;

assign acc_17_d0 = 32'd0;

assign acc_18_address0 = zext_ln45_fu_682_p1;

assign acc_18_d0 = 32'd0;

assign acc_19_address0 = zext_ln45_fu_682_p1;

assign acc_19_d0 = 32'd0;

assign acc_1_address0 = zext_ln45_fu_682_p1;

assign acc_1_d0 = 32'd0;

assign acc_20_address0 = zext_ln45_fu_682_p1;

assign acc_20_d0 = 32'd0;

assign acc_21_address0 = zext_ln45_fu_682_p1;

assign acc_21_d0 = 32'd0;

assign acc_22_address0 = zext_ln45_fu_682_p1;

assign acc_22_d0 = 32'd0;

assign acc_23_address0 = zext_ln45_fu_682_p1;

assign acc_23_d0 = 32'd0;

assign acc_24_address0 = zext_ln45_fu_682_p1;

assign acc_24_d0 = 32'd0;

assign acc_25_address0 = zext_ln45_fu_682_p1;

assign acc_25_d0 = 32'd0;

assign acc_26_address0 = zext_ln45_fu_682_p1;

assign acc_26_d0 = 32'd0;

assign acc_27_address0 = zext_ln45_fu_682_p1;

assign acc_27_d0 = 32'd0;

assign acc_28_address0 = zext_ln45_fu_682_p1;

assign acc_28_d0 = 32'd0;

assign acc_29_address0 = zext_ln45_fu_682_p1;

assign acc_29_d0 = 32'd0;

assign acc_2_address0 = zext_ln45_fu_682_p1;

assign acc_2_d0 = 32'd0;

assign acc_30_address0 = zext_ln45_fu_682_p1;

assign acc_30_d0 = 32'd0;

assign acc_31_address0 = zext_ln45_fu_682_p1;

assign acc_31_d0 = 32'd0;

assign acc_3_address0 = zext_ln45_fu_682_p1;

assign acc_3_d0 = 32'd0;

assign acc_4_address0 = zext_ln45_fu_682_p1;

assign acc_4_d0 = 32'd0;

assign acc_5_address0 = zext_ln45_fu_682_p1;

assign acc_5_d0 = 32'd0;

assign acc_6_address0 = zext_ln45_fu_682_p1;

assign acc_6_d0 = 32'd0;

assign acc_7_address0 = zext_ln45_fu_682_p1;

assign acc_7_d0 = 32'd0;

assign acc_8_address0 = zext_ln45_fu_682_p1;

assign acc_8_d0 = 32'd0;

assign acc_9_address0 = zext_ln45_fu_682_p1;

assign acc_9_d0 = 32'd0;

assign acc_address0 = zext_ln45_fu_682_p1;

assign acc_d0 = 32'd0;

assign add_ln45_1_fu_642_p2 = (ap_sig_allocacmp_indvar_flatten38_load + 11'd1);

assign add_ln45_fu_654_p2 = (ap_sig_allocacmp_i_load + 6'd1);

assign add_ln46_fu_722_p2 = (select_ln45_fu_666_p3 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln45_fu_636_p2 = ((ap_sig_allocacmp_indvar_flatten38_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_660_p2 = ((ap_sig_allocacmp_j_load == 6'd32) ? 1'b1 : 1'b0);

assign select_ln45_1_fu_674_p3 = ((icmp_ln46_fu_660_p2[0:0] == 1'b1) ? add_ln45_fu_654_p2 : ap_sig_allocacmp_i_load);

assign select_ln45_fu_666_p3 = ((icmp_ln46_fu_660_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln46_fu_718_p1 = select_ln45_fu_666_p3[4:0];

assign zext_ln45_fu_682_p1 = select_ln45_1_fu_674_p3;

endmodule //gemm_int8_gemm_int8_Pipeline_init_acc_VITIS_LOOP_46_2
