// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_int8_gemm_int8_Pipeline_VITIS_LOOP_70_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        Wtile_address0,
        Wtile_ce0,
        Wtile_we0,
        Wtile_d0,
        Wtile_31_address0,
        Wtile_31_ce0,
        Wtile_31_we0,
        Wtile_31_d0,
        Wtile_30_address0,
        Wtile_30_ce0,
        Wtile_30_we0,
        Wtile_30_d0,
        Wtile_29_address0,
        Wtile_29_ce0,
        Wtile_29_we0,
        Wtile_29_d0,
        Wtile_28_address0,
        Wtile_28_ce0,
        Wtile_28_we0,
        Wtile_28_d0,
        Wtile_27_address0,
        Wtile_27_ce0,
        Wtile_27_we0,
        Wtile_27_d0,
        Wtile_26_address0,
        Wtile_26_ce0,
        Wtile_26_we0,
        Wtile_26_d0,
        Wtile_25_address0,
        Wtile_25_ce0,
        Wtile_25_we0,
        Wtile_25_d0,
        Wtile_24_address0,
        Wtile_24_ce0,
        Wtile_24_we0,
        Wtile_24_d0,
        Wtile_23_address0,
        Wtile_23_ce0,
        Wtile_23_we0,
        Wtile_23_d0,
        Wtile_22_address0,
        Wtile_22_ce0,
        Wtile_22_we0,
        Wtile_22_d0,
        Wtile_21_address0,
        Wtile_21_ce0,
        Wtile_21_we0,
        Wtile_21_d0,
        Wtile_20_address0,
        Wtile_20_ce0,
        Wtile_20_we0,
        Wtile_20_d0,
        Wtile_19_address0,
        Wtile_19_ce0,
        Wtile_19_we0,
        Wtile_19_d0,
        Wtile_18_address0,
        Wtile_18_ce0,
        Wtile_18_we0,
        Wtile_18_d0,
        Wtile_17_address0,
        Wtile_17_ce0,
        Wtile_17_we0,
        Wtile_17_d0,
        Wtile_16_address0,
        Wtile_16_ce0,
        Wtile_16_we0,
        Wtile_16_d0,
        Wtile_15_address0,
        Wtile_15_ce0,
        Wtile_15_we0,
        Wtile_15_d0,
        Wtile_14_address0,
        Wtile_14_ce0,
        Wtile_14_we0,
        Wtile_14_d0,
        Wtile_13_address0,
        Wtile_13_ce0,
        Wtile_13_we0,
        Wtile_13_d0,
        Wtile_12_address0,
        Wtile_12_ce0,
        Wtile_12_we0,
        Wtile_12_d0,
        Wtile_11_address0,
        Wtile_11_ce0,
        Wtile_11_we0,
        Wtile_11_d0,
        Wtile_10_address0,
        Wtile_10_ce0,
        Wtile_10_we0,
        Wtile_10_d0,
        Wtile_9_address0,
        Wtile_9_ce0,
        Wtile_9_we0,
        Wtile_9_d0,
        Wtile_8_address0,
        Wtile_8_ce0,
        Wtile_8_we0,
        Wtile_8_d0,
        Wtile_7_address0,
        Wtile_7_ce0,
        Wtile_7_we0,
        Wtile_7_d0,
        Wtile_6_address0,
        Wtile_6_ce0,
        Wtile_6_we0,
        Wtile_6_d0,
        Wtile_5_address0,
        Wtile_5_ce0,
        Wtile_5_we0,
        Wtile_5_d0,
        Wtile_4_address0,
        Wtile_4_ce0,
        Wtile_4_we0,
        Wtile_4_d0,
        Wtile_3_address0,
        Wtile_3_ce0,
        Wtile_3_we0,
        Wtile_3_d0,
        Wtile_2_address0,
        Wtile_2_ce0,
        Wtile_2_we0,
        Wtile_2_d0,
        Wtile_1_address0,
        Wtile_1_ce0,
        Wtile_1_we0,
        Wtile_1_d0,
        zext_ln53,
        add_ln69
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
output  [4:0] Wtile_address0;
output   Wtile_ce0;
output   Wtile_we0;
output  [7:0] Wtile_d0;
output  [4:0] Wtile_31_address0;
output   Wtile_31_ce0;
output   Wtile_31_we0;
output  [7:0] Wtile_31_d0;
output  [4:0] Wtile_30_address0;
output   Wtile_30_ce0;
output   Wtile_30_we0;
output  [7:0] Wtile_30_d0;
output  [4:0] Wtile_29_address0;
output   Wtile_29_ce0;
output   Wtile_29_we0;
output  [7:0] Wtile_29_d0;
output  [4:0] Wtile_28_address0;
output   Wtile_28_ce0;
output   Wtile_28_we0;
output  [7:0] Wtile_28_d0;
output  [4:0] Wtile_27_address0;
output   Wtile_27_ce0;
output   Wtile_27_we0;
output  [7:0] Wtile_27_d0;
output  [4:0] Wtile_26_address0;
output   Wtile_26_ce0;
output   Wtile_26_we0;
output  [7:0] Wtile_26_d0;
output  [4:0] Wtile_25_address0;
output   Wtile_25_ce0;
output   Wtile_25_we0;
output  [7:0] Wtile_25_d0;
output  [4:0] Wtile_24_address0;
output   Wtile_24_ce0;
output   Wtile_24_we0;
output  [7:0] Wtile_24_d0;
output  [4:0] Wtile_23_address0;
output   Wtile_23_ce0;
output   Wtile_23_we0;
output  [7:0] Wtile_23_d0;
output  [4:0] Wtile_22_address0;
output   Wtile_22_ce0;
output   Wtile_22_we0;
output  [7:0] Wtile_22_d0;
output  [4:0] Wtile_21_address0;
output   Wtile_21_ce0;
output   Wtile_21_we0;
output  [7:0] Wtile_21_d0;
output  [4:0] Wtile_20_address0;
output   Wtile_20_ce0;
output   Wtile_20_we0;
output  [7:0] Wtile_20_d0;
output  [4:0] Wtile_19_address0;
output   Wtile_19_ce0;
output   Wtile_19_we0;
output  [7:0] Wtile_19_d0;
output  [4:0] Wtile_18_address0;
output   Wtile_18_ce0;
output   Wtile_18_we0;
output  [7:0] Wtile_18_d0;
output  [4:0] Wtile_17_address0;
output   Wtile_17_ce0;
output   Wtile_17_we0;
output  [7:0] Wtile_17_d0;
output  [4:0] Wtile_16_address0;
output   Wtile_16_ce0;
output   Wtile_16_we0;
output  [7:0] Wtile_16_d0;
output  [4:0] Wtile_15_address0;
output   Wtile_15_ce0;
output   Wtile_15_we0;
output  [7:0] Wtile_15_d0;
output  [4:0] Wtile_14_address0;
output   Wtile_14_ce0;
output   Wtile_14_we0;
output  [7:0] Wtile_14_d0;
output  [4:0] Wtile_13_address0;
output   Wtile_13_ce0;
output   Wtile_13_we0;
output  [7:0] Wtile_13_d0;
output  [4:0] Wtile_12_address0;
output   Wtile_12_ce0;
output   Wtile_12_we0;
output  [7:0] Wtile_12_d0;
output  [4:0] Wtile_11_address0;
output   Wtile_11_ce0;
output   Wtile_11_we0;
output  [7:0] Wtile_11_d0;
output  [4:0] Wtile_10_address0;
output   Wtile_10_ce0;
output   Wtile_10_we0;
output  [7:0] Wtile_10_d0;
output  [4:0] Wtile_9_address0;
output   Wtile_9_ce0;
output   Wtile_9_we0;
output  [7:0] Wtile_9_d0;
output  [4:0] Wtile_8_address0;
output   Wtile_8_ce0;
output   Wtile_8_we0;
output  [7:0] Wtile_8_d0;
output  [4:0] Wtile_7_address0;
output   Wtile_7_ce0;
output   Wtile_7_we0;
output  [7:0] Wtile_7_d0;
output  [4:0] Wtile_6_address0;
output   Wtile_6_ce0;
output   Wtile_6_we0;
output  [7:0] Wtile_6_d0;
output  [4:0] Wtile_5_address0;
output   Wtile_5_ce0;
output   Wtile_5_we0;
output  [7:0] Wtile_5_d0;
output  [4:0] Wtile_4_address0;
output   Wtile_4_ce0;
output   Wtile_4_we0;
output  [7:0] Wtile_4_d0;
output  [4:0] Wtile_3_address0;
output   Wtile_3_ce0;
output   Wtile_3_we0;
output  [7:0] Wtile_3_d0;
output  [4:0] Wtile_2_address0;
output   Wtile_2_ce0;
output   Wtile_2_we0;
output  [7:0] Wtile_2_d0;
output  [4:0] Wtile_1_address0;
output   Wtile_1_ce0;
output   Wtile_1_we0;
output  [7:0] Wtile_1_d0;
input  [9:0] zext_ln53;
input  [63:0] add_ln69;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg Wtile_ce0;
reg Wtile_we0;
reg Wtile_31_ce0;
reg Wtile_31_we0;
reg Wtile_30_ce0;
reg Wtile_30_we0;
reg Wtile_29_ce0;
reg Wtile_29_we0;
reg Wtile_28_ce0;
reg Wtile_28_we0;
reg Wtile_27_ce0;
reg Wtile_27_we0;
reg Wtile_26_ce0;
reg Wtile_26_we0;
reg Wtile_25_ce0;
reg Wtile_25_we0;
reg Wtile_24_ce0;
reg Wtile_24_we0;
reg Wtile_23_ce0;
reg Wtile_23_we0;
reg Wtile_22_ce0;
reg Wtile_22_we0;
reg Wtile_21_ce0;
reg Wtile_21_we0;
reg Wtile_20_ce0;
reg Wtile_20_we0;
reg Wtile_19_ce0;
reg Wtile_19_we0;
reg Wtile_18_ce0;
reg Wtile_18_we0;
reg Wtile_17_ce0;
reg Wtile_17_we0;
reg Wtile_16_ce0;
reg Wtile_16_we0;
reg Wtile_15_ce0;
reg Wtile_15_we0;
reg Wtile_14_ce0;
reg Wtile_14_we0;
reg Wtile_13_ce0;
reg Wtile_13_we0;
reg Wtile_12_ce0;
reg Wtile_12_we0;
reg Wtile_11_ce0;
reg Wtile_11_we0;
reg Wtile_10_ce0;
reg Wtile_10_we0;
reg Wtile_9_ce0;
reg Wtile_9_we0;
reg Wtile_8_ce0;
reg Wtile_8_we0;
reg Wtile_7_ce0;
reg Wtile_7_we0;
reg Wtile_6_ce0;
reg Wtile_6_we0;
reg Wtile_5_ce0;
reg Wtile_5_we0;
reg Wtile_4_ce0;
reg Wtile_4_we0;
reg Wtile_3_ce0;
reg Wtile_3_we0;
reg Wtile_2_ce0;
reg Wtile_2_we0;
reg Wtile_1_ce0;
reg Wtile_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] or_ln69_reg_928;
reg    ap_block_state2_io;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln69_fu_724_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_AR;
reg   [0:0] icmp_ln69_reg_924;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln69_fu_751_p2;
wire   [5:0] select_ln69_1_fu_765_p3;
reg   [5:0] select_ln69_1_reg_932;
reg   [5:0] select_ln69_1_reg_932_pp0_iter1_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter2_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter3_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter4_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter5_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter6_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter7_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter8_reg;
reg   [5:0] select_ln69_1_reg_932_pp0_iter9_reg;
reg   [63:0] gmem1_addr_reg_937;
wire   [4:0] trunc_ln70_fu_837_p1;
reg   [4:0] trunc_ln70_reg_942;
reg   [4:0] trunc_ln70_reg_942_pp0_iter1_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter2_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter3_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter4_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter5_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter6_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter7_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter8_reg;
reg   [4:0] trunc_ln70_reg_942_pp0_iter9_reg;
reg   [7:0] gmem1_addr_1_read_reg_951;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_657_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln69_2_fu_868_p1;
wire   [63:0] add_ln69_3_fu_825_p2;
reg   [5:0] kk_fu_202;
wire   [5:0] add_ln70_fu_847_p2;
reg   [5:0] ap_sig_allocacmp_kk_load;
reg   [5:0] j_1_fu_206;
reg   [5:0] ap_sig_allocacmp_j;
reg   [10:0] indvar_flatten118_fu_210;
wire   [10:0] add_ln69_4_fu_730_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten118_load;
wire   [4:0] trunc_ln69_fu_690_p1;
wire   [14:0] shl_ln2_fu_694_p3;
wire   [12:0] shl_ln69_1_fu_706_p3;
wire   [15:0] zext_ln69_fu_702_p1;
wire   [15:0] zext_ln69_1_fu_714_p1;
wire   [0:0] icmp_ln70_fu_745_p2;
wire   [5:0] add_ln69_1_fu_739_p2;
wire   [4:0] trunc_ln69_1_fu_773_p1;
wire   [14:0] shl_ln69_mid1_fu_777_p3;
wire   [12:0] shl_ln69_1_mid1_fu_789_p3;
wire   [15:0] zext_ln69_3_fu_785_p1;
wire   [15:0] zext_ln69_4_fu_797_p1;
wire   [15:0] sub_ln69_1_fu_801_p2;
wire   [15:0] sub_ln69_fu_718_p2;
wire   [15:0] zext_ln53_cast_fu_665_p1;
wire   [15:0] select_ln69_2_fu_807_p3;
wire   [15:0] add_ln69_2_fu_815_p2;
wire  signed [63:0] sext_ln69_fu_821_p1;
wire   [5:0] select_ln69_fu_757_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_815;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gemm_int8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_724_p2 == 1'd0))) begin
            indvar_flatten118_fu_210 <= add_ln69_4_fu_730_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten118_fu_210 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_724_p2 == 1'd0))) begin
            j_1_fu_206 <= select_ln69_1_fu_765_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_206 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_724_p2 == 1'd0))) begin
            kk_fu_202 <= add_ln70_fu_847_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kk_fu_202 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln69_reg_924 <= icmp_ln69_fu_724_p2;
        select_ln69_1_reg_932_pp0_iter1_reg <= select_ln69_1_reg_932;
        trunc_ln70_reg_942_pp0_iter1_reg <= trunc_ln70_reg_942;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem1_addr_1_read_reg_951 <= m_axi_gmem1_RDATA;
        select_ln69_1_reg_932_pp0_iter2_reg <= select_ln69_1_reg_932_pp0_iter1_reg;
        select_ln69_1_reg_932_pp0_iter3_reg <= select_ln69_1_reg_932_pp0_iter2_reg;
        select_ln69_1_reg_932_pp0_iter4_reg <= select_ln69_1_reg_932_pp0_iter3_reg;
        select_ln69_1_reg_932_pp0_iter5_reg <= select_ln69_1_reg_932_pp0_iter4_reg;
        select_ln69_1_reg_932_pp0_iter6_reg <= select_ln69_1_reg_932_pp0_iter5_reg;
        select_ln69_1_reg_932_pp0_iter7_reg <= select_ln69_1_reg_932_pp0_iter6_reg;
        select_ln69_1_reg_932_pp0_iter8_reg <= select_ln69_1_reg_932_pp0_iter7_reg;
        select_ln69_1_reg_932_pp0_iter9_reg <= select_ln69_1_reg_932_pp0_iter8_reg;
        trunc_ln70_reg_942_pp0_iter2_reg <= trunc_ln70_reg_942_pp0_iter1_reg;
        trunc_ln70_reg_942_pp0_iter3_reg <= trunc_ln70_reg_942_pp0_iter2_reg;
        trunc_ln70_reg_942_pp0_iter4_reg <= trunc_ln70_reg_942_pp0_iter3_reg;
        trunc_ln70_reg_942_pp0_iter5_reg <= trunc_ln70_reg_942_pp0_iter4_reg;
        trunc_ln70_reg_942_pp0_iter6_reg <= trunc_ln70_reg_942_pp0_iter5_reg;
        trunc_ln70_reg_942_pp0_iter7_reg <= trunc_ln70_reg_942_pp0_iter6_reg;
        trunc_ln70_reg_942_pp0_iter8_reg <= trunc_ln70_reg_942_pp0_iter7_reg;
        trunc_ln70_reg_942_pp0_iter9_reg <= trunc_ln70_reg_942_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln69_fu_751_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_724_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem1_addr_reg_937 <= add_ln69_3_fu_825_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_724_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln69_reg_928 <= or_ln69_fu_751_p2;
        select_ln69_1_reg_932 <= select_ln69_1_fu_765_p3;
        trunc_ln70_reg_942 <= trunc_ln70_fu_837_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_10_ce0 = 1'b1;
    end else begin
        Wtile_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_10_we0 = 1'b1;
    end else begin
        Wtile_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_11_ce0 = 1'b1;
    end else begin
        Wtile_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_11_we0 = 1'b1;
    end else begin
        Wtile_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_12_ce0 = 1'b1;
    end else begin
        Wtile_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_12_we0 = 1'b1;
    end else begin
        Wtile_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_13_ce0 = 1'b1;
    end else begin
        Wtile_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_13_we0 = 1'b1;
    end else begin
        Wtile_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_14_ce0 = 1'b1;
    end else begin
        Wtile_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_14_we0 = 1'b1;
    end else begin
        Wtile_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_15_ce0 = 1'b1;
    end else begin
        Wtile_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_15_we0 = 1'b1;
    end else begin
        Wtile_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_16_ce0 = 1'b1;
    end else begin
        Wtile_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_16_we0 = 1'b1;
    end else begin
        Wtile_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_17_ce0 = 1'b1;
    end else begin
        Wtile_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_17_we0 = 1'b1;
    end else begin
        Wtile_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_18_ce0 = 1'b1;
    end else begin
        Wtile_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_18_we0 = 1'b1;
    end else begin
        Wtile_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_19_ce0 = 1'b1;
    end else begin
        Wtile_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_19_we0 = 1'b1;
    end else begin
        Wtile_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_1_ce0 = 1'b1;
    end else begin
        Wtile_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_1_we0 = 1'b1;
    end else begin
        Wtile_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_20_ce0 = 1'b1;
    end else begin
        Wtile_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd20) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_20_we0 = 1'b1;
    end else begin
        Wtile_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_21_ce0 = 1'b1;
    end else begin
        Wtile_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd21) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_21_we0 = 1'b1;
    end else begin
        Wtile_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_22_ce0 = 1'b1;
    end else begin
        Wtile_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd22) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_22_we0 = 1'b1;
    end else begin
        Wtile_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_23_ce0 = 1'b1;
    end else begin
        Wtile_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd23) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_23_we0 = 1'b1;
    end else begin
        Wtile_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_24_ce0 = 1'b1;
    end else begin
        Wtile_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_24_we0 = 1'b1;
    end else begin
        Wtile_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_25_ce0 = 1'b1;
    end else begin
        Wtile_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd25) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_25_we0 = 1'b1;
    end else begin
        Wtile_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_26_ce0 = 1'b1;
    end else begin
        Wtile_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd26) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_26_we0 = 1'b1;
    end else begin
        Wtile_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_27_ce0 = 1'b1;
    end else begin
        Wtile_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd27) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_27_we0 = 1'b1;
    end else begin
        Wtile_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_28_ce0 = 1'b1;
    end else begin
        Wtile_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd28) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_28_we0 = 1'b1;
    end else begin
        Wtile_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_29_ce0 = 1'b1;
    end else begin
        Wtile_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd29) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_29_we0 = 1'b1;
    end else begin
        Wtile_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_2_ce0 = 1'b1;
    end else begin
        Wtile_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_2_we0 = 1'b1;
    end else begin
        Wtile_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_30_ce0 = 1'b1;
    end else begin
        Wtile_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd30) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_30_we0 = 1'b1;
    end else begin
        Wtile_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_31_ce0 = 1'b1;
    end else begin
        Wtile_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd31) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_31_we0 = 1'b1;
    end else begin
        Wtile_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_3_ce0 = 1'b1;
    end else begin
        Wtile_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_3_we0 = 1'b1;
    end else begin
        Wtile_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_4_ce0 = 1'b1;
    end else begin
        Wtile_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_4_we0 = 1'b1;
    end else begin
        Wtile_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_5_ce0 = 1'b1;
    end else begin
        Wtile_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_5_we0 = 1'b1;
    end else begin
        Wtile_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_6_ce0 = 1'b1;
    end else begin
        Wtile_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_6_we0 = 1'b1;
    end else begin
        Wtile_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_7_ce0 = 1'b1;
    end else begin
        Wtile_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_7_we0 = 1'b1;
    end else begin
        Wtile_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_8_ce0 = 1'b1;
    end else begin
        Wtile_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_8_we0 = 1'b1;
    end else begin
        Wtile_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_9_ce0 = 1'b1;
    end else begin
        Wtile_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_9_we0 = 1'b1;
    end else begin
        Wtile_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_ce0 = 1'b1;
    end else begin
        Wtile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln70_reg_942_pp0_iter9_reg == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Wtile_we0 = 1'b1;
    end else begin
        Wtile_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_724_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_first_iter_0_phi_fu_657_p4 = 1'd1;
        end else if ((1'b1 == ap_condition_815)) begin
            ap_phi_mux_first_iter_0_phi_fu_657_p4 = 1'd0;
        end else begin
            ap_phi_mux_first_iter_0_phi_fu_657_p4 = 1'd1;
        end
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_657_p4 = 1'd1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten118_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten118_load = indvar_flatten118_fu_210;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j = 6'd0;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_206;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_kk_load = 6'd0;
    end else begin
        ap_sig_allocacmp_kk_load = kk_fu_202;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (or_ln69_reg_928 == 1'd1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln69_reg_928 == 1'd1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Wtile_10_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_10_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_11_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_11_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_12_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_12_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_13_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_13_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_14_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_14_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_15_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_15_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_16_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_16_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_17_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_17_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_18_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_18_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_19_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_19_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_1_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_1_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_20_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_20_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_21_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_21_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_22_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_22_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_23_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_23_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_24_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_24_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_25_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_25_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_26_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_26_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_27_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_27_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_28_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_28_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_29_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_29_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_2_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_2_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_30_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_30_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_31_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_31_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_3_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_3_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_4_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_4_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_5_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_5_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_6_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_6_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_7_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_7_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_8_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_8_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_9_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_9_d0 = gmem1_addr_1_read_reg_951;

assign Wtile_address0 = zext_ln69_2_fu_868_p1;

assign Wtile_d0 = gmem1_addr_1_read_reg_951;

assign add_ln69_1_fu_739_p2 = (ap_sig_allocacmp_j + 6'd1);

assign add_ln69_2_fu_815_p2 = (zext_ln53_cast_fu_665_p1 + select_ln69_2_fu_807_p3);

assign add_ln69_3_fu_825_p2 = ($signed(sext_ln69_fu_821_p1) + $signed(add_ln69));

assign add_ln69_4_fu_730_p2 = (ap_sig_allocacmp_indvar_flatten118_load + 11'd1);

assign add_ln70_fu_847_p2 = (select_ln69_fu_757_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem1_ARREADY == 1'b0) & (or_ln69_reg_928 == 1'd1));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_815 = ((icmp_ln69_reg_924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln69_fu_724_p2 = ((ap_sig_allocacmp_indvar_flatten118_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_745_p2 = ((ap_sig_allocacmp_kk_load == 6'd32) ? 1'b1 : 1'b0);

assign m_axi_gmem1_ARADDR = gmem1_addr_reg_937;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd32;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 8'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 1'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign or_ln69_fu_751_p2 = (icmp_ln70_fu_745_p2 | ap_phi_mux_first_iter_0_phi_fu_657_p4);

assign select_ln69_1_fu_765_p3 = ((icmp_ln70_fu_745_p2[0:0] == 1'b1) ? add_ln69_1_fu_739_p2 : ap_sig_allocacmp_j);

assign select_ln69_2_fu_807_p3 = ((icmp_ln70_fu_745_p2[0:0] == 1'b1) ? sub_ln69_1_fu_801_p2 : sub_ln69_fu_718_p2);

assign select_ln69_fu_757_p3 = ((icmp_ln70_fu_745_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_kk_load);

assign sext_ln69_fu_821_p1 = $signed(add_ln69_2_fu_815_p2);

assign shl_ln2_fu_694_p3 = {{trunc_ln69_fu_690_p1}, {10'd0}};

assign shl_ln69_1_fu_706_p3 = {{trunc_ln69_fu_690_p1}, {8'd0}};

assign shl_ln69_1_mid1_fu_789_p3 = {{trunc_ln69_1_fu_773_p1}, {8'd0}};

assign shl_ln69_mid1_fu_777_p3 = {{trunc_ln69_1_fu_773_p1}, {10'd0}};

assign sub_ln69_1_fu_801_p2 = (zext_ln69_3_fu_785_p1 - zext_ln69_4_fu_797_p1);

assign sub_ln69_fu_718_p2 = (zext_ln69_fu_702_p1 - zext_ln69_1_fu_714_p1);

assign trunc_ln69_1_fu_773_p1 = add_ln69_1_fu_739_p2[4:0];

assign trunc_ln69_fu_690_p1 = ap_sig_allocacmp_j[4:0];

assign trunc_ln70_fu_837_p1 = select_ln69_fu_757_p3[4:0];

assign zext_ln53_cast_fu_665_p1 = zext_ln53;

assign zext_ln69_1_fu_714_p1 = shl_ln69_1_fu_706_p3;

assign zext_ln69_2_fu_868_p1 = select_ln69_1_reg_932_pp0_iter9_reg;

assign zext_ln69_3_fu_785_p1 = shl_ln69_mid1_fu_777_p3;

assign zext_ln69_4_fu_797_p1 = shl_ln69_1_mid1_fu_789_p3;

assign zext_ln69_fu_702_p1 = shl_ln2_fu_694_p3;

endmodule //gemm_int8_gemm_int8_Pipeline_VITIS_LOOP_70_4
