# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prototipo_1/prototipo_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1 || ORIG_REF_NAME==prototipo_1} -quiet] -quiet

# IP: bd/prototipo_1/ip/prototipo_1_zynq_ultra_ps_e_0_0/prototipo_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==prototipo_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/prototipo_1/ip/prototipo_1_gemm_int8_0_1/prototipo_1_gemm_int8_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1_gemm_int8_0_1 || ORIG_REF_NAME==prototipo_1_gemm_int8_0_1} -quiet] -quiet

# IP: bd/prototipo_1/ip/prototipo_1_rst_ps8_0_99M_0/prototipo_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==prototipo_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/prototipo_1/ip/prototipo_1_smartconnect_0_0/prototipo_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1_smartconnect_0_0 || ORIG_REF_NAME==prototipo_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/prototipo_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prototipo_1_smartconnect_0_1 || ORIG_REF_NAME==prototipo_1_smartconnect_0_1} -quiet] -quiet

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/prototipo_1_ooc.xdc
