# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.srcs/sources_1/bd/prototipo_1/ip/prototipo_1_gemm_int8_0_1/prototipo_1_gemm_int8_0_1.xci
# IP: The module: 'prototipo_1_gemm_int8_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_gemm_int8_0_1/constraints/gemm_int8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototipo_1_gemm_int8_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.srcs/sources_1/bd/prototipo_1/ip/prototipo_1_gemm_int8_0_1/prototipo_1_gemm_int8_0_1.xci
# IP: The module: 'prototipo_1_gemm_int8_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_gemm_int8_0_1/constraints/gemm_int8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototipo_1_gemm_int8_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
