# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.srcs/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/prototipo_1_smartconnect_0_1.xci
# IP: The module: 'prototipo_1_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/bd_77cd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_0/bd_77cd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_2/bd_77cd_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_3/bd_77cd_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_4/bd_77cd_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_5/bd_77cd_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_6/bd_77cd_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_7/bd_77cd_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_8/bd_77cd_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_9/bd_77cd_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_10/bd_77cd_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_11/bd_77cd_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_12/bd_77cd_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_13/bd_77cd_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_14/bd_77cd_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_15/bd_77cd_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_16/bd_77cd_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_17/bd_77cd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_18/bd_77cd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_19/bd_77cd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_20/bd_77cd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_21/bd_77cd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_22/bd_77cd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_23/bd_77cd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_24/bd_77cd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_25/bd_77cd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_26/bd_77cd_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_27/bd_77cd_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_28/bd_77cd_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_29/bd_77cd_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_30/bd_77cd_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_31/bd_77cd_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_32/bd_77cd_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_33/bd_77cd_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_34/bd_77cd_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_35/bd_77cd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_36/bd_77cd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_37/bd_77cd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_38/bd_77cd_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_39/bd_77cd_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_40/bd_77cd_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_41/bd_77cd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_2/bd_77cd_arinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_3/bd_77cd_rinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_4/bd_77cd_awinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_5/bd_77cd_winsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_6/bd_77cd_binsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_7/bd_77cd_aroutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_8/bd_77cd_routsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_9/bd_77cd_awoutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_10/bd_77cd_woutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_11/bd_77cd_boutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_12/bd_77cd_arni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_13/bd_77cd_rni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_14/bd_77cd_awni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_15/bd_77cd_wni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_16/bd_77cd_bni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_20/bd_77cd_s00a2s_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_21/bd_77cd_sarn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_22/bd_77cd_srn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_23/bd_77cd_sawn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_24/bd_77cd_swn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_25/bd_77cd_sbn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_29/bd_77cd_s01a2s_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_30/bd_77cd_sarn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_31/bd_77cd_srn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_32/bd_77cd_sawn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_33/bd_77cd_swn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_34/bd_77cd_sbn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_35/bd_77cd_m00s2a_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_36/bd_77cd_m00arn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_37/bd_77cd_m00rn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_38/bd_77cd_m00awn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_39/bd_77cd_m00wn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_40/bd_77cd_m00bn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototipo_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.srcs/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/prototipo_1_smartconnect_0_1.xci
# IP: The module: 'prototipo_1_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/bd_77cd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_0/bd_77cd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_2/bd_77cd_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_3/bd_77cd_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_4/bd_77cd_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_5/bd_77cd_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_6/bd_77cd_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_7/bd_77cd_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_8/bd_77cd_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_9/bd_77cd_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_10/bd_77cd_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_11/bd_77cd_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_12/bd_77cd_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_13/bd_77cd_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_14/bd_77cd_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_15/bd_77cd_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_16/bd_77cd_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_17/bd_77cd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_18/bd_77cd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_19/bd_77cd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_20/bd_77cd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_21/bd_77cd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_22/bd_77cd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_23/bd_77cd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_24/bd_77cd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_25/bd_77cd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_26/bd_77cd_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_27/bd_77cd_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_28/bd_77cd_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_29/bd_77cd_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_30/bd_77cd_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_31/bd_77cd_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_32/bd_77cd_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_33/bd_77cd_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_34/bd_77cd_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_35/bd_77cd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_36/bd_77cd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_37/bd_77cd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_38/bd_77cd_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_39/bd_77cd_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_40/bd_77cd_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_41/bd_77cd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_1/bd_77cd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_2/bd_77cd_arinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_3/bd_77cd_rinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_4/bd_77cd_awinsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_5/bd_77cd_winsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_6/bd_77cd_binsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_7/bd_77cd_aroutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_8/bd_77cd_routsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_9/bd_77cd_awoutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_10/bd_77cd_woutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_11/bd_77cd_boutsw_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_12/bd_77cd_arni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_13/bd_77cd_rni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_14/bd_77cd_awni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_15/bd_77cd_wni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_16/bd_77cd_bni_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_20/bd_77cd_s00a2s_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_21/bd_77cd_sarn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_22/bd_77cd_srn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_23/bd_77cd_sawn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_24/bd_77cd_swn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_25/bd_77cd_sbn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_29/bd_77cd_s01a2s_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_30/bd_77cd_sarn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_31/bd_77cd_srn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_32/bd_77cd_sawn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_33/bd_77cd_swn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_34/bd_77cd_sbn_1_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_35/bd_77cd_m00s2a_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_36/bd_77cd_m00arn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_37/bd_77cd_m00rn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_38/bd_77cd_m00awn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_39/bd_77cd_m00wn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/bd_0/ip/ip_40/bd_77cd_m00bn_0_ooc.xdc

# XDC: /home/dolv07/gemm-beto-kv260/hw_design/vivado/gemm_beto_kv260/gemm_beto_kv260.gen/sources_1/bd/prototipo_1/ip/prototipo_1_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototipo_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
