-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gemm_int8_gemm_int8_Pipeline_load_Xtile_VITIS_LOOP_62_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Xtile_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_ce0 : OUT STD_LOGIC;
    Xtile_we0 : OUT STD_LOGIC;
    Xtile_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    trunc_ln37_mid2 : IN STD_LOGIC_VECTOR (5 downto 0);
    Xtile_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_31_ce0 : OUT STD_LOGIC;
    Xtile_31_we0 : OUT STD_LOGIC;
    Xtile_31_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_30_ce0 : OUT STD_LOGIC;
    Xtile_30_we0 : OUT STD_LOGIC;
    Xtile_30_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_29_ce0 : OUT STD_LOGIC;
    Xtile_29_we0 : OUT STD_LOGIC;
    Xtile_29_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_28_ce0 : OUT STD_LOGIC;
    Xtile_28_we0 : OUT STD_LOGIC;
    Xtile_28_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_27_ce0 : OUT STD_LOGIC;
    Xtile_27_we0 : OUT STD_LOGIC;
    Xtile_27_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_26_ce0 : OUT STD_LOGIC;
    Xtile_26_we0 : OUT STD_LOGIC;
    Xtile_26_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_25_ce0 : OUT STD_LOGIC;
    Xtile_25_we0 : OUT STD_LOGIC;
    Xtile_25_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_24_ce0 : OUT STD_LOGIC;
    Xtile_24_we0 : OUT STD_LOGIC;
    Xtile_24_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_23_ce0 : OUT STD_LOGIC;
    Xtile_23_we0 : OUT STD_LOGIC;
    Xtile_23_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_22_ce0 : OUT STD_LOGIC;
    Xtile_22_we0 : OUT STD_LOGIC;
    Xtile_22_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_21_ce0 : OUT STD_LOGIC;
    Xtile_21_we0 : OUT STD_LOGIC;
    Xtile_21_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_20_ce0 : OUT STD_LOGIC;
    Xtile_20_we0 : OUT STD_LOGIC;
    Xtile_20_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_19_ce0 : OUT STD_LOGIC;
    Xtile_19_we0 : OUT STD_LOGIC;
    Xtile_19_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_18_ce0 : OUT STD_LOGIC;
    Xtile_18_we0 : OUT STD_LOGIC;
    Xtile_18_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_17_ce0 : OUT STD_LOGIC;
    Xtile_17_we0 : OUT STD_LOGIC;
    Xtile_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_16_ce0 : OUT STD_LOGIC;
    Xtile_16_we0 : OUT STD_LOGIC;
    Xtile_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_15_ce0 : OUT STD_LOGIC;
    Xtile_15_we0 : OUT STD_LOGIC;
    Xtile_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_14_ce0 : OUT STD_LOGIC;
    Xtile_14_we0 : OUT STD_LOGIC;
    Xtile_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_13_ce0 : OUT STD_LOGIC;
    Xtile_13_we0 : OUT STD_LOGIC;
    Xtile_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_12_ce0 : OUT STD_LOGIC;
    Xtile_12_we0 : OUT STD_LOGIC;
    Xtile_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_11_ce0 : OUT STD_LOGIC;
    Xtile_11_we0 : OUT STD_LOGIC;
    Xtile_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_10_ce0 : OUT STD_LOGIC;
    Xtile_10_we0 : OUT STD_LOGIC;
    Xtile_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_9_ce0 : OUT STD_LOGIC;
    Xtile_9_we0 : OUT STD_LOGIC;
    Xtile_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_8_ce0 : OUT STD_LOGIC;
    Xtile_8_we0 : OUT STD_LOGIC;
    Xtile_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_7_ce0 : OUT STD_LOGIC;
    Xtile_7_we0 : OUT STD_LOGIC;
    Xtile_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_6_ce0 : OUT STD_LOGIC;
    Xtile_6_we0 : OUT STD_LOGIC;
    Xtile_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_5_ce0 : OUT STD_LOGIC;
    Xtile_5_we0 : OUT STD_LOGIC;
    Xtile_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_4_ce0 : OUT STD_LOGIC;
    Xtile_4_we0 : OUT STD_LOGIC;
    Xtile_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_3_ce0 : OUT STD_LOGIC;
    Xtile_3_we0 : OUT STD_LOGIC;
    Xtile_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_2_ce0 : OUT STD_LOGIC;
    Xtile_2_we0 : OUT STD_LOGIC;
    Xtile_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Xtile_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Xtile_1_ce0 : OUT STD_LOGIC;
    Xtile_1_we0 : OUT STD_LOGIC;
    Xtile_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    k0 : IN STD_LOGIC_VECTOR (9 downto 0);
    Xbuf_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    Xbuf_ce0 : OUT STD_LOGIC;
    Xbuf_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of gemm_int8_gemm_int8_Pipeline_load_Xtile_VITIS_LOOP_62_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln61_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln61_1_fu_725_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln61_1_reg_874 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln62_fu_769_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln62_reg_879 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_2_fu_789_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln61_fu_815_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kk_fu_184 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln62_fu_794_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_kk_load : STD_LOGIC_VECTOR (5 downto 0);
    signal i_fu_188 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten77_fu_192 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln61_2_fu_693_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten77_load : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln62_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln61_fu_705_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln61_1_fu_733_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_747_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_7_fu_739_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln64_fu_755_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln61_fu_717_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln62_fu_765_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln64_fu_773_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln64_fu_759_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln64_1_fu_779_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln64_1_fu_783_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gemm_int8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gemm_int8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln61_fu_687_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_188 <= select_ln61_1_fu_725_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_188 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten77_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln61_fu_687_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten77_fu_192 <= add_ln61_2_fu_693_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten77_fu_192 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    kk_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln61_fu_687_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    kk_fu_184 <= add_ln62_fu_794_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kk_fu_184 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_687_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln61_1_reg_874 <= select_ln61_1_fu_725_p3;
                trunc_ln62_reg_879 <= trunc_ln62_fu_769_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Xbuf_address0 <= zext_ln64_2_fu_789_p1(16 - 1 downto 0);

    Xbuf_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xbuf_ce0 <= ap_const_logic_1;
        else 
            Xbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_10_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_10_ce0 <= ap_const_logic_1;
        else 
            Xtile_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_10_d0 <= Xbuf_q0;

    Xtile_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_10_we0 <= ap_const_logic_1;
        else 
            Xtile_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_11_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_11_ce0 <= ap_const_logic_1;
        else 
            Xtile_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_11_d0 <= Xbuf_q0;

    Xtile_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_11_we0 <= ap_const_logic_1;
        else 
            Xtile_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_12_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_12_ce0 <= ap_const_logic_1;
        else 
            Xtile_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_12_d0 <= Xbuf_q0;

    Xtile_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_12_we0 <= ap_const_logic_1;
        else 
            Xtile_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_13_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_13_ce0 <= ap_const_logic_1;
        else 
            Xtile_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_13_d0 <= Xbuf_q0;

    Xtile_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_13_we0 <= ap_const_logic_1;
        else 
            Xtile_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_14_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_14_ce0 <= ap_const_logic_1;
        else 
            Xtile_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_14_d0 <= Xbuf_q0;

    Xtile_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_14_we0 <= ap_const_logic_1;
        else 
            Xtile_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_15_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_15_ce0 <= ap_const_logic_1;
        else 
            Xtile_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_15_d0 <= Xbuf_q0;

    Xtile_15_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_15_we0 <= ap_const_logic_1;
        else 
            Xtile_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_16_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_16_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_16_ce0 <= ap_const_logic_1;
        else 
            Xtile_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_16_d0 <= Xbuf_q0;

    Xtile_16_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_16_we0 <= ap_const_logic_1;
        else 
            Xtile_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_17_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_17_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_17_ce0 <= ap_const_logic_1;
        else 
            Xtile_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_17_d0 <= Xbuf_q0;

    Xtile_17_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_11) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_17_we0 <= ap_const_logic_1;
        else 
            Xtile_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_18_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_18_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_18_ce0 <= ap_const_logic_1;
        else 
            Xtile_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_18_d0 <= Xbuf_q0;

    Xtile_18_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_18_we0 <= ap_const_logic_1;
        else 
            Xtile_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_19_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_19_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_19_ce0 <= ap_const_logic_1;
        else 
            Xtile_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_19_d0 <= Xbuf_q0;

    Xtile_19_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_13) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_19_we0 <= ap_const_logic_1;
        else 
            Xtile_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_1_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_1_ce0 <= ap_const_logic_1;
        else 
            Xtile_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_1_d0 <= Xbuf_q0;

    Xtile_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_1_we0 <= ap_const_logic_1;
        else 
            Xtile_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_20_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_20_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_20_ce0 <= ap_const_logic_1;
        else 
            Xtile_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_20_d0 <= Xbuf_q0;

    Xtile_20_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_20_we0 <= ap_const_logic_1;
        else 
            Xtile_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_21_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_21_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_21_ce0 <= ap_const_logic_1;
        else 
            Xtile_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_21_d0 <= Xbuf_q0;

    Xtile_21_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_21_we0 <= ap_const_logic_1;
        else 
            Xtile_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_22_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_22_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_22_ce0 <= ap_const_logic_1;
        else 
            Xtile_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_22_d0 <= Xbuf_q0;

    Xtile_22_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_22_we0 <= ap_const_logic_1;
        else 
            Xtile_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_23_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_23_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_23_ce0 <= ap_const_logic_1;
        else 
            Xtile_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_23_d0 <= Xbuf_q0;

    Xtile_23_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_17) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_23_we0 <= ap_const_logic_1;
        else 
            Xtile_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_24_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_24_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_24_ce0 <= ap_const_logic_1;
        else 
            Xtile_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_24_d0 <= Xbuf_q0;

    Xtile_24_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_24_we0 <= ap_const_logic_1;
        else 
            Xtile_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_25_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_25_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_25_ce0 <= ap_const_logic_1;
        else 
            Xtile_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_25_d0 <= Xbuf_q0;

    Xtile_25_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_19) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_25_we0 <= ap_const_logic_1;
        else 
            Xtile_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_26_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_26_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_26_ce0 <= ap_const_logic_1;
        else 
            Xtile_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_26_d0 <= Xbuf_q0;

    Xtile_26_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_26_we0 <= ap_const_logic_1;
        else 
            Xtile_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_27_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_27_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_27_ce0 <= ap_const_logic_1;
        else 
            Xtile_27_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_27_d0 <= Xbuf_q0;

    Xtile_27_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_27_we0 <= ap_const_logic_1;
        else 
            Xtile_27_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_28_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_28_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_28_ce0 <= ap_const_logic_1;
        else 
            Xtile_28_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_28_d0 <= Xbuf_q0;

    Xtile_28_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_28_we0 <= ap_const_logic_1;
        else 
            Xtile_28_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_29_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_29_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_29_ce0 <= ap_const_logic_1;
        else 
            Xtile_29_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_29_d0 <= Xbuf_q0;

    Xtile_29_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_29_we0 <= ap_const_logic_1;
        else 
            Xtile_29_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_2_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_2_ce0 <= ap_const_logic_1;
        else 
            Xtile_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_2_d0 <= Xbuf_q0;

    Xtile_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_2_we0 <= ap_const_logic_1;
        else 
            Xtile_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_30_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_30_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_30_ce0 <= ap_const_logic_1;
        else 
            Xtile_30_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_30_d0 <= Xbuf_q0;

    Xtile_30_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_30_we0 <= ap_const_logic_1;
        else 
            Xtile_30_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_31_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_31_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_31_ce0 <= ap_const_logic_1;
        else 
            Xtile_31_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_31_d0 <= Xbuf_q0;

    Xtile_31_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_1F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_31_we0 <= ap_const_logic_1;
        else 
            Xtile_31_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_3_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_3_ce0 <= ap_const_logic_1;
        else 
            Xtile_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_3_d0 <= Xbuf_q0;

    Xtile_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_3_we0 <= ap_const_logic_1;
        else 
            Xtile_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_4_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_4_ce0 <= ap_const_logic_1;
        else 
            Xtile_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_4_d0 <= Xbuf_q0;

    Xtile_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_4_we0 <= ap_const_logic_1;
        else 
            Xtile_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_5_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_5_ce0 <= ap_const_logic_1;
        else 
            Xtile_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_5_d0 <= Xbuf_q0;

    Xtile_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_5_we0 <= ap_const_logic_1;
        else 
            Xtile_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_6_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_6_ce0 <= ap_const_logic_1;
        else 
            Xtile_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_6_d0 <= Xbuf_q0;

    Xtile_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_6_we0 <= ap_const_logic_1;
        else 
            Xtile_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_7_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_7_ce0 <= ap_const_logic_1;
        else 
            Xtile_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_7_d0 <= Xbuf_q0;

    Xtile_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_7_we0 <= ap_const_logic_1;
        else 
            Xtile_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_8_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_8_ce0 <= ap_const_logic_1;
        else 
            Xtile_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_8_d0 <= Xbuf_q0;

    Xtile_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_8_we0 <= ap_const_logic_1;
        else 
            Xtile_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_9_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_9_ce0 <= ap_const_logic_1;
        else 
            Xtile_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_9_d0 <= Xbuf_q0;

    Xtile_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_9) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_9_we0 <= ap_const_logic_1;
        else 
            Xtile_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_address0 <= zext_ln61_fu_815_p1(5 - 1 downto 0);

    Xtile_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_ce0 <= ap_const_logic_1;
        else 
            Xtile_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Xtile_d0 <= Xbuf_q0;

    Xtile_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln62_reg_879)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln62_reg_879 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Xtile_we0 <= ap_const_logic_1;
        else 
            Xtile_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln61_1_fu_733_p2 <= std_logic_vector(unsigned(select_ln61_1_fu_725_p3) + unsigned(trunc_ln37_mid2));
    add_ln61_2_fu_693_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten77_load) + unsigned(ap_const_lv11_1));
    add_ln61_fu_705_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv6_1));
    add_ln62_fu_794_p2 <= std_logic_vector(unsigned(select_ln61_fu_717_p3) + unsigned(ap_const_lv6_1));
    add_ln64_1_fu_783_p2 <= std_logic_vector(unsigned(sub_ln64_fu_759_p2) + unsigned(zext_ln64_1_fu_779_p1));
    add_ln64_fu_773_p2 <= std_logic_vector(unsigned(zext_ln62_fu_765_p1) + unsigned(k0));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln61_fu_687_p2)
    begin
        if (((icmp_ln61_fu_687_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_188)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_188;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten77_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten77_fu_192)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten77_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten77_load <= indvar_flatten77_fu_192;
        end if; 
    end process;


    ap_sig_allocacmp_kk_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, kk_fu_184, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_kk_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_kk_load <= kk_fu_184;
        end if; 
    end process;

    icmp_ln61_fu_687_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten77_load = ap_const_lv11_400) else "0";
    icmp_ln62_fu_711_p2 <= "1" when (ap_sig_allocacmp_kk_load = ap_const_lv6_20) else "0";
    select_ln61_1_fu_725_p3 <= 
        add_ln61_fu_705_p2 when (icmp_ln62_fu_711_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln61_fu_717_p3 <= 
        ap_const_lv6_0 when (icmp_ln62_fu_711_p2(0) = '1') else 
        ap_sig_allocacmp_kk_load;
    sub_ln64_fu_759_p2 <= std_logic_vector(unsigned(tmp_7_fu_739_p3) - unsigned(zext_ln64_fu_755_p1));
    tmp_7_fu_739_p3 <= (add_ln61_1_fu_733_p2 & ap_const_lv10_0);
    tmp_8_fu_747_p3 <= (add_ln61_1_fu_733_p2 & ap_const_lv8_0);
    trunc_ln62_fu_769_p1 <= select_ln61_fu_717_p3(5 - 1 downto 0);
    zext_ln61_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln61_1_reg_874),64));
    zext_ln62_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln61_fu_717_p3),10));
    zext_ln64_1_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_fu_773_p2),16));
    zext_ln64_2_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_1_fu_783_p2),64));
    zext_ln64_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_747_p3),16));
end behav;
