-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gemm_int8_gemm_int8_Pipeline_VITIS_LOOP_70_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    Wtile_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_ce0 : OUT STD_LOGIC;
    Wtile_we0 : OUT STD_LOGIC;
    Wtile_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_31_ce0 : OUT STD_LOGIC;
    Wtile_31_we0 : OUT STD_LOGIC;
    Wtile_31_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_30_ce0 : OUT STD_LOGIC;
    Wtile_30_we0 : OUT STD_LOGIC;
    Wtile_30_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_29_ce0 : OUT STD_LOGIC;
    Wtile_29_we0 : OUT STD_LOGIC;
    Wtile_29_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_28_ce0 : OUT STD_LOGIC;
    Wtile_28_we0 : OUT STD_LOGIC;
    Wtile_28_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_27_ce0 : OUT STD_LOGIC;
    Wtile_27_we0 : OUT STD_LOGIC;
    Wtile_27_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_26_ce0 : OUT STD_LOGIC;
    Wtile_26_we0 : OUT STD_LOGIC;
    Wtile_26_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_25_ce0 : OUT STD_LOGIC;
    Wtile_25_we0 : OUT STD_LOGIC;
    Wtile_25_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_24_ce0 : OUT STD_LOGIC;
    Wtile_24_we0 : OUT STD_LOGIC;
    Wtile_24_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_23_ce0 : OUT STD_LOGIC;
    Wtile_23_we0 : OUT STD_LOGIC;
    Wtile_23_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_22_ce0 : OUT STD_LOGIC;
    Wtile_22_we0 : OUT STD_LOGIC;
    Wtile_22_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_21_ce0 : OUT STD_LOGIC;
    Wtile_21_we0 : OUT STD_LOGIC;
    Wtile_21_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_20_ce0 : OUT STD_LOGIC;
    Wtile_20_we0 : OUT STD_LOGIC;
    Wtile_20_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_19_ce0 : OUT STD_LOGIC;
    Wtile_19_we0 : OUT STD_LOGIC;
    Wtile_19_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_18_ce0 : OUT STD_LOGIC;
    Wtile_18_we0 : OUT STD_LOGIC;
    Wtile_18_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_17_ce0 : OUT STD_LOGIC;
    Wtile_17_we0 : OUT STD_LOGIC;
    Wtile_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_16_ce0 : OUT STD_LOGIC;
    Wtile_16_we0 : OUT STD_LOGIC;
    Wtile_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_15_ce0 : OUT STD_LOGIC;
    Wtile_15_we0 : OUT STD_LOGIC;
    Wtile_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_14_ce0 : OUT STD_LOGIC;
    Wtile_14_we0 : OUT STD_LOGIC;
    Wtile_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_13_ce0 : OUT STD_LOGIC;
    Wtile_13_we0 : OUT STD_LOGIC;
    Wtile_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_12_ce0 : OUT STD_LOGIC;
    Wtile_12_we0 : OUT STD_LOGIC;
    Wtile_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_11_ce0 : OUT STD_LOGIC;
    Wtile_11_we0 : OUT STD_LOGIC;
    Wtile_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_10_ce0 : OUT STD_LOGIC;
    Wtile_10_we0 : OUT STD_LOGIC;
    Wtile_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_9_ce0 : OUT STD_LOGIC;
    Wtile_9_we0 : OUT STD_LOGIC;
    Wtile_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_8_ce0 : OUT STD_LOGIC;
    Wtile_8_we0 : OUT STD_LOGIC;
    Wtile_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_7_ce0 : OUT STD_LOGIC;
    Wtile_7_we0 : OUT STD_LOGIC;
    Wtile_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_6_ce0 : OUT STD_LOGIC;
    Wtile_6_we0 : OUT STD_LOGIC;
    Wtile_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_5_ce0 : OUT STD_LOGIC;
    Wtile_5_we0 : OUT STD_LOGIC;
    Wtile_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_4_ce0 : OUT STD_LOGIC;
    Wtile_4_we0 : OUT STD_LOGIC;
    Wtile_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_3_ce0 : OUT STD_LOGIC;
    Wtile_3_we0 : OUT STD_LOGIC;
    Wtile_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_2_ce0 : OUT STD_LOGIC;
    Wtile_2_we0 : OUT STD_LOGIC;
    Wtile_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    Wtile_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Wtile_1_ce0 : OUT STD_LOGIC;
    Wtile_1_we0 : OUT STD_LOGIC;
    Wtile_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    zext_ln53 : IN STD_LOGIC_VECTOR (9 downto 0);
    add_ln69 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of gemm_int8_gemm_int8_Pipeline_VITIS_LOOP_70_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal or_ln69_reg_928 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln69_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal icmp_ln69_reg_924 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln69_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln69_1_fu_765_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln69_1_reg_932_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal gmem1_addr_reg_937 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln70_fu_837_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln70_reg_942_pp0_iter9_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal gmem1_addr_1_read_reg_951 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_first_iter_0_phi_fu_657_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln69_2_fu_868_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln69_3_fu_825_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal kk_fu_202 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln70_fu_847_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_kk_load : STD_LOGIC_VECTOR (5 downto 0);
    signal j_1_fu_206 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten118_fu_210 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln69_4_fu_730_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten118_load : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln69_fu_690_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln2_fu_694_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln69_1_fu_706_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln69_fu_702_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln69_1_fu_714_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln70_fu_745_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln69_1_fu_739_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln69_1_fu_773_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln69_mid1_fu_777_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln69_1_mid1_fu_789_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln69_3_fu_785_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln69_4_fu_797_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln69_1_fu_801_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln69_fu_718_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln53_cast_fu_665_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln69_2_fu_807_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln69_2_fu_815_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln69_fu_821_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln69_fu_757_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_815 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component gemm_int8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gemm_int8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten118_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln69_fu_724_p2 = ap_const_lv1_0))) then 
                    indvar_flatten118_fu_210 <= add_ln69_4_fu_730_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten118_fu_210 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    j_1_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln69_fu_724_p2 = ap_const_lv1_0))) then 
                    j_1_fu_206 <= select_ln69_1_fu_765_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_206 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    kk_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln69_fu_724_p2 = ap_const_lv1_0))) then 
                    kk_fu_202 <= add_ln70_fu_847_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kk_fu_202 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln69_reg_924 <= icmp_ln69_fu_724_p2;
                select_ln69_1_reg_932_pp0_iter1_reg <= select_ln69_1_reg_932;
                trunc_ln70_reg_942_pp0_iter1_reg <= trunc_ln70_reg_942;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem1_addr_1_read_reg_951 <= m_axi_gmem1_RDATA;
                select_ln69_1_reg_932_pp0_iter2_reg <= select_ln69_1_reg_932_pp0_iter1_reg;
                select_ln69_1_reg_932_pp0_iter3_reg <= select_ln69_1_reg_932_pp0_iter2_reg;
                select_ln69_1_reg_932_pp0_iter4_reg <= select_ln69_1_reg_932_pp0_iter3_reg;
                select_ln69_1_reg_932_pp0_iter5_reg <= select_ln69_1_reg_932_pp0_iter4_reg;
                select_ln69_1_reg_932_pp0_iter6_reg <= select_ln69_1_reg_932_pp0_iter5_reg;
                select_ln69_1_reg_932_pp0_iter7_reg <= select_ln69_1_reg_932_pp0_iter6_reg;
                select_ln69_1_reg_932_pp0_iter8_reg <= select_ln69_1_reg_932_pp0_iter7_reg;
                select_ln69_1_reg_932_pp0_iter9_reg <= select_ln69_1_reg_932_pp0_iter8_reg;
                trunc_ln70_reg_942_pp0_iter2_reg <= trunc_ln70_reg_942_pp0_iter1_reg;
                trunc_ln70_reg_942_pp0_iter3_reg <= trunc_ln70_reg_942_pp0_iter2_reg;
                trunc_ln70_reg_942_pp0_iter4_reg <= trunc_ln70_reg_942_pp0_iter3_reg;
                trunc_ln70_reg_942_pp0_iter5_reg <= trunc_ln70_reg_942_pp0_iter4_reg;
                trunc_ln70_reg_942_pp0_iter6_reg <= trunc_ln70_reg_942_pp0_iter5_reg;
                trunc_ln70_reg_942_pp0_iter7_reg <= trunc_ln70_reg_942_pp0_iter6_reg;
                trunc_ln70_reg_942_pp0_iter8_reg <= trunc_ln70_reg_942_pp0_iter7_reg;
                trunc_ln70_reg_942_pp0_iter9_reg <= trunc_ln70_reg_942_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln69_fu_751_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln69_fu_724_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gmem1_addr_reg_937 <= add_ln69_3_fu_825_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln69_fu_724_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_ln69_reg_928 <= or_ln69_fu_751_p2;
                select_ln69_1_reg_932 <= select_ln69_1_fu_765_p3;
                trunc_ln70_reg_942 <= trunc_ln70_fu_837_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Wtile_10_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_10_ce0 <= ap_const_logic_1;
        else 
            Wtile_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_10_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_10_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_10_we0 <= ap_const_logic_1;
        else 
            Wtile_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_11_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_11_ce0 <= ap_const_logic_1;
        else 
            Wtile_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_11_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_11_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_11_we0 <= ap_const_logic_1;
        else 
            Wtile_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_12_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_12_ce0 <= ap_const_logic_1;
        else 
            Wtile_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_12_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_12_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_12_we0 <= ap_const_logic_1;
        else 
            Wtile_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_13_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_13_ce0 <= ap_const_logic_1;
        else 
            Wtile_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_13_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_13_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_D) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_13_we0 <= ap_const_logic_1;
        else 
            Wtile_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_14_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_14_ce0 <= ap_const_logic_1;
        else 
            Wtile_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_14_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_14_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_E) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_14_we0 <= ap_const_logic_1;
        else 
            Wtile_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_15_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_15_ce0 <= ap_const_logic_1;
        else 
            Wtile_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_15_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_15_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_F) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_15_we0 <= ap_const_logic_1;
        else 
            Wtile_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_16_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_16_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_16_ce0 <= ap_const_logic_1;
        else 
            Wtile_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_16_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_16_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_10) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_16_we0 <= ap_const_logic_1;
        else 
            Wtile_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_17_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_17_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_17_ce0 <= ap_const_logic_1;
        else 
            Wtile_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_17_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_17_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_11) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_17_we0 <= ap_const_logic_1;
        else 
            Wtile_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_18_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_18_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_18_ce0 <= ap_const_logic_1;
        else 
            Wtile_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_18_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_18_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_12) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_18_we0 <= ap_const_logic_1;
        else 
            Wtile_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_19_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_19_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_19_ce0 <= ap_const_logic_1;
        else 
            Wtile_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_19_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_19_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_13) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_19_we0 <= ap_const_logic_1;
        else 
            Wtile_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_1_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_1_ce0 <= ap_const_logic_1;
        else 
            Wtile_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_1_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_1_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_1_we0 <= ap_const_logic_1;
        else 
            Wtile_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_20_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_20_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_20_ce0 <= ap_const_logic_1;
        else 
            Wtile_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_20_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_20_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_14) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_20_we0 <= ap_const_logic_1;
        else 
            Wtile_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_21_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_21_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_21_ce0 <= ap_const_logic_1;
        else 
            Wtile_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_21_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_21_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_15) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_21_we0 <= ap_const_logic_1;
        else 
            Wtile_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_22_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_22_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_22_ce0 <= ap_const_logic_1;
        else 
            Wtile_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_22_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_22_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_16) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_22_we0 <= ap_const_logic_1;
        else 
            Wtile_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_23_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_23_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_23_ce0 <= ap_const_logic_1;
        else 
            Wtile_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_23_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_23_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_17) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_23_we0 <= ap_const_logic_1;
        else 
            Wtile_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_24_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_24_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_24_ce0 <= ap_const_logic_1;
        else 
            Wtile_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_24_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_24_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_18) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_24_we0 <= ap_const_logic_1;
        else 
            Wtile_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_25_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_25_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_25_ce0 <= ap_const_logic_1;
        else 
            Wtile_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_25_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_25_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_19) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_25_we0 <= ap_const_logic_1;
        else 
            Wtile_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_26_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_26_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_26_ce0 <= ap_const_logic_1;
        else 
            Wtile_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_26_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_26_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_26_we0 <= ap_const_logic_1;
        else 
            Wtile_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_27_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_27_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_27_ce0 <= ap_const_logic_1;
        else 
            Wtile_27_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_27_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_27_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_27_we0 <= ap_const_logic_1;
        else 
            Wtile_27_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_28_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_28_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_28_ce0 <= ap_const_logic_1;
        else 
            Wtile_28_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_28_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_28_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_28_we0 <= ap_const_logic_1;
        else 
            Wtile_28_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_29_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_29_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_29_ce0 <= ap_const_logic_1;
        else 
            Wtile_29_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_29_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_29_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1D) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_29_we0 <= ap_const_logic_1;
        else 
            Wtile_29_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_2_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_2_ce0 <= ap_const_logic_1;
        else 
            Wtile_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_2_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_2_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_2_we0 <= ap_const_logic_1;
        else 
            Wtile_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_30_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_30_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_30_ce0 <= ap_const_logic_1;
        else 
            Wtile_30_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_30_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_30_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1E) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_30_we0 <= ap_const_logic_1;
        else 
            Wtile_30_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_31_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_31_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_31_ce0 <= ap_const_logic_1;
        else 
            Wtile_31_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_31_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_31_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_1F) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_31_we0 <= ap_const_logic_1;
        else 
            Wtile_31_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_3_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_3_ce0 <= ap_const_logic_1;
        else 
            Wtile_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_3_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_3_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_3_we0 <= ap_const_logic_1;
        else 
            Wtile_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_4_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_4_ce0 <= ap_const_logic_1;
        else 
            Wtile_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_4_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_4_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_4_we0 <= ap_const_logic_1;
        else 
            Wtile_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_5_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_5_ce0 <= ap_const_logic_1;
        else 
            Wtile_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_5_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_5_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_5_we0 <= ap_const_logic_1;
        else 
            Wtile_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_6_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_6_ce0 <= ap_const_logic_1;
        else 
            Wtile_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_6_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_6_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_6_we0 <= ap_const_logic_1;
        else 
            Wtile_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_7_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_7_ce0 <= ap_const_logic_1;
        else 
            Wtile_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_7_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_7_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_7_we0 <= ap_const_logic_1;
        else 
            Wtile_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_8_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_8_ce0 <= ap_const_logic_1;
        else 
            Wtile_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_8_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_8_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_8) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_8_we0 <= ap_const_logic_1;
        else 
            Wtile_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_9_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_9_ce0 <= ap_const_logic_1;
        else 
            Wtile_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_9_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_9_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_9) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_9_we0 <= ap_const_logic_1;
        else 
            Wtile_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_address0 <= zext_ln69_2_fu_868_p1(5 - 1 downto 0);

    Wtile_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_ce0 <= ap_const_logic_1;
        else 
            Wtile_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Wtile_d0 <= gmem1_addr_1_read_reg_951;

    Wtile_we0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln70_reg_942_pp0_iter9_reg)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln70_reg_942_pp0_iter9_reg = ap_const_lv5_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Wtile_we0 <= ap_const_logic_1;
        else 
            Wtile_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln69_1_fu_739_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv6_1));
    add_ln69_2_fu_815_p2 <= std_logic_vector(unsigned(zext_ln53_cast_fu_665_p1) + unsigned(select_ln69_2_fu_807_p3));
    add_ln69_3_fu_825_p2 <= std_logic_vector(signed(sext_ln69_fu_821_p1) + signed(add_ln69));
    add_ln69_4_fu_730_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten118_load) + unsigned(ap_const_lv11_1));
    add_ln70_fu_847_p2 <= std_logic_vector(unsigned(select_ln69_fu_757_p3) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem1_RVALID, ap_block_state2_io)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem1_RVALID, ap_block_state2_io)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmem1_RVALID)
    begin
                ap_block_state10_pp0_stage0_iter9 <= (m_axi_gmem1_RVALID = ap_const_logic_0);
    end process;

        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_io_assign_proc : process(m_axi_gmem1_ARREADY, or_ln69_reg_928)
    begin
                ap_block_state2_io <= ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (or_ln69_reg_928 = ap_const_lv1_1));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_815_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln69_reg_924)
    begin
                ap_condition_815 <= ((icmp_ln69_reg_924 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln69_fu_724_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln69_fu_724_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_first_iter_0_phi_fu_657_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_condition_815)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_first_iter_0_phi_fu_657_p4 <= ap_const_lv1_1;
            elsif ((ap_const_boolean_1 = ap_condition_815)) then 
                ap_phi_mux_first_iter_0_phi_fu_657_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_first_iter_0_phi_fu_657_p4 <= ap_const_lv1_1;
            end if;
        else 
            ap_phi_mux_first_iter_0_phi_fu_657_p4 <= ap_const_lv1_1;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten118_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten118_fu_210)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten118_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten118_load <= indvar_flatten118_fu_210;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_1_fu_206)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j <= j_1_fu_206;
        end if; 
    end process;


    ap_sig_allocacmp_kk_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, kk_fu_202)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_kk_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_kk_load <= kk_fu_202;
        end if; 
    end process;


    gmem1_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_ARREADY, or_ln69_reg_928, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln69_reg_928 = ap_const_lv1_1))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln69_fu_724_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten118_load = ap_const_lv11_400) else "0";
    icmp_ln70_fu_745_p2 <= "1" when (ap_sig_allocacmp_kk_load = ap_const_lv6_20) else "0";
    m_axi_gmem1_ARADDR <= gmem1_addr_reg_937;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_20;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_ln69_reg_928, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln69_reg_928 = ap_const_lv1_1))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv8_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv1_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    or_ln69_fu_751_p2 <= (icmp_ln70_fu_745_p2 or ap_phi_mux_first_iter_0_phi_fu_657_p4);
    select_ln69_1_fu_765_p3 <= 
        add_ln69_1_fu_739_p2 when (icmp_ln70_fu_745_p2(0) = '1') else 
        ap_sig_allocacmp_j;
    select_ln69_2_fu_807_p3 <= 
        sub_ln69_1_fu_801_p2 when (icmp_ln70_fu_745_p2(0) = '1') else 
        sub_ln69_fu_718_p2;
    select_ln69_fu_757_p3 <= 
        ap_const_lv6_0 when (icmp_ln70_fu_745_p2(0) = '1') else 
        ap_sig_allocacmp_kk_load;
        sext_ln69_fu_821_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln69_2_fu_815_p2),64));

    shl_ln2_fu_694_p3 <= (trunc_ln69_fu_690_p1 & ap_const_lv10_0);
    shl_ln69_1_fu_706_p3 <= (trunc_ln69_fu_690_p1 & ap_const_lv8_0);
    shl_ln69_1_mid1_fu_789_p3 <= (trunc_ln69_1_fu_773_p1 & ap_const_lv8_0);
    shl_ln69_mid1_fu_777_p3 <= (trunc_ln69_1_fu_773_p1 & ap_const_lv10_0);
    sub_ln69_1_fu_801_p2 <= std_logic_vector(unsigned(zext_ln69_3_fu_785_p1) - unsigned(zext_ln69_4_fu_797_p1));
    sub_ln69_fu_718_p2 <= std_logic_vector(unsigned(zext_ln69_fu_702_p1) - unsigned(zext_ln69_1_fu_714_p1));
    trunc_ln69_1_fu_773_p1 <= add_ln69_1_fu_739_p2(5 - 1 downto 0);
    trunc_ln69_fu_690_p1 <= ap_sig_allocacmp_j(5 - 1 downto 0);
    trunc_ln70_fu_837_p1 <= select_ln69_fu_757_p3(5 - 1 downto 0);
    zext_ln53_cast_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln53),16));
    zext_ln69_1_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln69_1_fu_706_p3),16));
    zext_ln69_2_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln69_1_reg_932_pp0_iter9_reg),64));
    zext_ln69_3_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln69_mid1_fu_777_p3),16));
    zext_ln69_4_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln69_1_mid1_fu_789_p3),16));
    zext_ln69_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_694_p3),16));
end behav;
