
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgemm_int8.h"

/*
* The configuration table for devices
*/

XGemm_int8_Config XGemm_int8_ConfigTable[XPAR_XGEMM_INT8_NUM_INSTANCES] =
{
	{
		XPAR_GEMM_INT8_0_DEVICE_ID,
		XPAR_GEMM_INT8_0_S_AXI_CONTROL_BASEADDR
	}
};


