// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gemm_int8_gemm_int8_Pipeline_load_Xtile_VITIS_LOOP_62_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Xtile_address0,
        Xtile_ce0,
        Xtile_we0,
        Xtile_d0,
        trunc_ln37_mid2,
        Xtile_31_address0,
        Xtile_31_ce0,
        Xtile_31_we0,
        Xtile_31_d0,
        Xtile_30_address0,
        Xtile_30_ce0,
        Xtile_30_we0,
        Xtile_30_d0,
        Xtile_29_address0,
        Xtile_29_ce0,
        Xtile_29_we0,
        Xtile_29_d0,
        Xtile_28_address0,
        Xtile_28_ce0,
        Xtile_28_we0,
        Xtile_28_d0,
        Xtile_27_address0,
        Xtile_27_ce0,
        Xtile_27_we0,
        Xtile_27_d0,
        Xtile_26_address0,
        Xtile_26_ce0,
        Xtile_26_we0,
        Xtile_26_d0,
        Xtile_25_address0,
        Xtile_25_ce0,
        Xtile_25_we0,
        Xtile_25_d0,
        Xtile_24_address0,
        Xtile_24_ce0,
        Xtile_24_we0,
        Xtile_24_d0,
        Xtile_23_address0,
        Xtile_23_ce0,
        Xtile_23_we0,
        Xtile_23_d0,
        Xtile_22_address0,
        Xtile_22_ce0,
        Xtile_22_we0,
        Xtile_22_d0,
        Xtile_21_address0,
        Xtile_21_ce0,
        Xtile_21_we0,
        Xtile_21_d0,
        Xtile_20_address0,
        Xtile_20_ce0,
        Xtile_20_we0,
        Xtile_20_d0,
        Xtile_19_address0,
        Xtile_19_ce0,
        Xtile_19_we0,
        Xtile_19_d0,
        Xtile_18_address0,
        Xtile_18_ce0,
        Xtile_18_we0,
        Xtile_18_d0,
        Xtile_17_address0,
        Xtile_17_ce0,
        Xtile_17_we0,
        Xtile_17_d0,
        Xtile_16_address0,
        Xtile_16_ce0,
        Xtile_16_we0,
        Xtile_16_d0,
        Xtile_15_address0,
        Xtile_15_ce0,
        Xtile_15_we0,
        Xtile_15_d0,
        Xtile_14_address0,
        Xtile_14_ce0,
        Xtile_14_we0,
        Xtile_14_d0,
        Xtile_13_address0,
        Xtile_13_ce0,
        Xtile_13_we0,
        Xtile_13_d0,
        Xtile_12_address0,
        Xtile_12_ce0,
        Xtile_12_we0,
        Xtile_12_d0,
        Xtile_11_address0,
        Xtile_11_ce0,
        Xtile_11_we0,
        Xtile_11_d0,
        Xtile_10_address0,
        Xtile_10_ce0,
        Xtile_10_we0,
        Xtile_10_d0,
        Xtile_9_address0,
        Xtile_9_ce0,
        Xtile_9_we0,
        Xtile_9_d0,
        Xtile_8_address0,
        Xtile_8_ce0,
        Xtile_8_we0,
        Xtile_8_d0,
        Xtile_7_address0,
        Xtile_7_ce0,
        Xtile_7_we0,
        Xtile_7_d0,
        Xtile_6_address0,
        Xtile_6_ce0,
        Xtile_6_we0,
        Xtile_6_d0,
        Xtile_5_address0,
        Xtile_5_ce0,
        Xtile_5_we0,
        Xtile_5_d0,
        Xtile_4_address0,
        Xtile_4_ce0,
        Xtile_4_we0,
        Xtile_4_d0,
        Xtile_3_address0,
        Xtile_3_ce0,
        Xtile_3_we0,
        Xtile_3_d0,
        Xtile_2_address0,
        Xtile_2_ce0,
        Xtile_2_we0,
        Xtile_2_d0,
        Xtile_1_address0,
        Xtile_1_ce0,
        Xtile_1_we0,
        Xtile_1_d0,
        k0,
        Xbuf_address0,
        Xbuf_ce0,
        Xbuf_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] Xtile_address0;
output   Xtile_ce0;
output   Xtile_we0;
output  [7:0] Xtile_d0;
input  [5:0] trunc_ln37_mid2;
output  [4:0] Xtile_31_address0;
output   Xtile_31_ce0;
output   Xtile_31_we0;
output  [7:0] Xtile_31_d0;
output  [4:0] Xtile_30_address0;
output   Xtile_30_ce0;
output   Xtile_30_we0;
output  [7:0] Xtile_30_d0;
output  [4:0] Xtile_29_address0;
output   Xtile_29_ce0;
output   Xtile_29_we0;
output  [7:0] Xtile_29_d0;
output  [4:0] Xtile_28_address0;
output   Xtile_28_ce0;
output   Xtile_28_we0;
output  [7:0] Xtile_28_d0;
output  [4:0] Xtile_27_address0;
output   Xtile_27_ce0;
output   Xtile_27_we0;
output  [7:0] Xtile_27_d0;
output  [4:0] Xtile_26_address0;
output   Xtile_26_ce0;
output   Xtile_26_we0;
output  [7:0] Xtile_26_d0;
output  [4:0] Xtile_25_address0;
output   Xtile_25_ce0;
output   Xtile_25_we0;
output  [7:0] Xtile_25_d0;
output  [4:0] Xtile_24_address0;
output   Xtile_24_ce0;
output   Xtile_24_we0;
output  [7:0] Xtile_24_d0;
output  [4:0] Xtile_23_address0;
output   Xtile_23_ce0;
output   Xtile_23_we0;
output  [7:0] Xtile_23_d0;
output  [4:0] Xtile_22_address0;
output   Xtile_22_ce0;
output   Xtile_22_we0;
output  [7:0] Xtile_22_d0;
output  [4:0] Xtile_21_address0;
output   Xtile_21_ce0;
output   Xtile_21_we0;
output  [7:0] Xtile_21_d0;
output  [4:0] Xtile_20_address0;
output   Xtile_20_ce0;
output   Xtile_20_we0;
output  [7:0] Xtile_20_d0;
output  [4:0] Xtile_19_address0;
output   Xtile_19_ce0;
output   Xtile_19_we0;
output  [7:0] Xtile_19_d0;
output  [4:0] Xtile_18_address0;
output   Xtile_18_ce0;
output   Xtile_18_we0;
output  [7:0] Xtile_18_d0;
output  [4:0] Xtile_17_address0;
output   Xtile_17_ce0;
output   Xtile_17_we0;
output  [7:0] Xtile_17_d0;
output  [4:0] Xtile_16_address0;
output   Xtile_16_ce0;
output   Xtile_16_we0;
output  [7:0] Xtile_16_d0;
output  [4:0] Xtile_15_address0;
output   Xtile_15_ce0;
output   Xtile_15_we0;
output  [7:0] Xtile_15_d0;
output  [4:0] Xtile_14_address0;
output   Xtile_14_ce0;
output   Xtile_14_we0;
output  [7:0] Xtile_14_d0;
output  [4:0] Xtile_13_address0;
output   Xtile_13_ce0;
output   Xtile_13_we0;
output  [7:0] Xtile_13_d0;
output  [4:0] Xtile_12_address0;
output   Xtile_12_ce0;
output   Xtile_12_we0;
output  [7:0] Xtile_12_d0;
output  [4:0] Xtile_11_address0;
output   Xtile_11_ce0;
output   Xtile_11_we0;
output  [7:0] Xtile_11_d0;
output  [4:0] Xtile_10_address0;
output   Xtile_10_ce0;
output   Xtile_10_we0;
output  [7:0] Xtile_10_d0;
output  [4:0] Xtile_9_address0;
output   Xtile_9_ce0;
output   Xtile_9_we0;
output  [7:0] Xtile_9_d0;
output  [4:0] Xtile_8_address0;
output   Xtile_8_ce0;
output   Xtile_8_we0;
output  [7:0] Xtile_8_d0;
output  [4:0] Xtile_7_address0;
output   Xtile_7_ce0;
output   Xtile_7_we0;
output  [7:0] Xtile_7_d0;
output  [4:0] Xtile_6_address0;
output   Xtile_6_ce0;
output   Xtile_6_we0;
output  [7:0] Xtile_6_d0;
output  [4:0] Xtile_5_address0;
output   Xtile_5_ce0;
output   Xtile_5_we0;
output  [7:0] Xtile_5_d0;
output  [4:0] Xtile_4_address0;
output   Xtile_4_ce0;
output   Xtile_4_we0;
output  [7:0] Xtile_4_d0;
output  [4:0] Xtile_3_address0;
output   Xtile_3_ce0;
output   Xtile_3_we0;
output  [7:0] Xtile_3_d0;
output  [4:0] Xtile_2_address0;
output   Xtile_2_ce0;
output   Xtile_2_we0;
output  [7:0] Xtile_2_d0;
output  [4:0] Xtile_1_address0;
output   Xtile_1_ce0;
output   Xtile_1_we0;
output  [7:0] Xtile_1_d0;
input  [9:0] k0;
output  [15:0] Xbuf_address0;
output   Xbuf_ce0;
input  [7:0] Xbuf_q0;

reg ap_idle;
reg Xtile_ce0;
reg Xtile_we0;
reg Xtile_31_ce0;
reg Xtile_31_we0;
reg Xtile_30_ce0;
reg Xtile_30_we0;
reg Xtile_29_ce0;
reg Xtile_29_we0;
reg Xtile_28_ce0;
reg Xtile_28_we0;
reg Xtile_27_ce0;
reg Xtile_27_we0;
reg Xtile_26_ce0;
reg Xtile_26_we0;
reg Xtile_25_ce0;
reg Xtile_25_we0;
reg Xtile_24_ce0;
reg Xtile_24_we0;
reg Xtile_23_ce0;
reg Xtile_23_we0;
reg Xtile_22_ce0;
reg Xtile_22_we0;
reg Xtile_21_ce0;
reg Xtile_21_we0;
reg Xtile_20_ce0;
reg Xtile_20_we0;
reg Xtile_19_ce0;
reg Xtile_19_we0;
reg Xtile_18_ce0;
reg Xtile_18_we0;
reg Xtile_17_ce0;
reg Xtile_17_we0;
reg Xtile_16_ce0;
reg Xtile_16_we0;
reg Xtile_15_ce0;
reg Xtile_15_we0;
reg Xtile_14_ce0;
reg Xtile_14_we0;
reg Xtile_13_ce0;
reg Xtile_13_we0;
reg Xtile_12_ce0;
reg Xtile_12_we0;
reg Xtile_11_ce0;
reg Xtile_11_we0;
reg Xtile_10_ce0;
reg Xtile_10_we0;
reg Xtile_9_ce0;
reg Xtile_9_we0;
reg Xtile_8_ce0;
reg Xtile_8_we0;
reg Xtile_7_ce0;
reg Xtile_7_we0;
reg Xtile_6_ce0;
reg Xtile_6_we0;
reg Xtile_5_ce0;
reg Xtile_5_we0;
reg Xtile_4_ce0;
reg Xtile_4_we0;
reg Xtile_3_ce0;
reg Xtile_3_we0;
reg Xtile_2_ce0;
reg Xtile_2_we0;
reg Xtile_1_ce0;
reg Xtile_1_we0;
reg Xbuf_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln61_fu_687_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] select_ln61_1_fu_725_p3;
reg   [5:0] select_ln61_1_reg_874;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] trunc_ln62_fu_769_p1;
reg   [4:0] trunc_ln62_reg_879;
wire   [63:0] zext_ln64_2_fu_789_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln61_fu_815_p1;
reg   [5:0] kk_fu_184;
wire   [5:0] add_ln62_fu_794_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_kk_load;
reg   [5:0] i_fu_188;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [10:0] indvar_flatten77_fu_192;
wire   [10:0] add_ln61_2_fu_693_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten77_load;
wire   [0:0] icmp_ln62_fu_711_p2;
wire   [5:0] add_ln61_fu_705_p2;
wire   [5:0] add_ln61_1_fu_733_p2;
wire   [13:0] tmp_8_fu_747_p3;
wire   [15:0] tmp_7_fu_739_p3;
wire   [15:0] zext_ln64_fu_755_p1;
wire   [5:0] select_ln61_fu_717_p3;
wire   [9:0] zext_ln62_fu_765_p1;
wire   [9:0] add_ln64_fu_773_p2;
wire   [15:0] sub_ln64_fu_759_p2;
wire   [15:0] zext_ln64_1_fu_779_p1;
wire   [15:0] add_ln64_1_fu_783_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gemm_int8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_687_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_188 <= select_ln61_1_fu_725_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_188 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_687_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten77_fu_192 <= add_ln61_2_fu_693_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten77_fu_192 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln61_fu_687_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            kk_fu_184 <= add_ln62_fu_794_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kk_fu_184 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_687_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln61_1_reg_874 <= select_ln61_1_fu_725_p3;
        trunc_ln62_reg_879 <= trunc_ln62_fu_769_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xbuf_ce0 = 1'b1;
    end else begin
        Xbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_10_ce0 = 1'b1;
    end else begin
        Xtile_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_10_we0 = 1'b1;
    end else begin
        Xtile_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_11_ce0 = 1'b1;
    end else begin
        Xtile_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_11_we0 = 1'b1;
    end else begin
        Xtile_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_12_ce0 = 1'b1;
    end else begin
        Xtile_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_12_we0 = 1'b1;
    end else begin
        Xtile_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_13_ce0 = 1'b1;
    end else begin
        Xtile_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_13_we0 = 1'b1;
    end else begin
        Xtile_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_14_ce0 = 1'b1;
    end else begin
        Xtile_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_14_we0 = 1'b1;
    end else begin
        Xtile_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_15_ce0 = 1'b1;
    end else begin
        Xtile_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_15_we0 = 1'b1;
    end else begin
        Xtile_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_16_ce0 = 1'b1;
    end else begin
        Xtile_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_16_we0 = 1'b1;
    end else begin
        Xtile_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_17_ce0 = 1'b1;
    end else begin
        Xtile_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd17) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_17_we0 = 1'b1;
    end else begin
        Xtile_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_18_ce0 = 1'b1;
    end else begin
        Xtile_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_18_we0 = 1'b1;
    end else begin
        Xtile_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_19_ce0 = 1'b1;
    end else begin
        Xtile_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd19) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_19_we0 = 1'b1;
    end else begin
        Xtile_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_1_ce0 = 1'b1;
    end else begin
        Xtile_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_1_we0 = 1'b1;
    end else begin
        Xtile_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_20_ce0 = 1'b1;
    end else begin
        Xtile_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_20_we0 = 1'b1;
    end else begin
        Xtile_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_21_ce0 = 1'b1;
    end else begin
        Xtile_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd21) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_21_we0 = 1'b1;
    end else begin
        Xtile_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_22_ce0 = 1'b1;
    end else begin
        Xtile_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_22_we0 = 1'b1;
    end else begin
        Xtile_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_23_ce0 = 1'b1;
    end else begin
        Xtile_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd23) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_23_we0 = 1'b1;
    end else begin
        Xtile_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_24_ce0 = 1'b1;
    end else begin
        Xtile_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd24) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_24_we0 = 1'b1;
    end else begin
        Xtile_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_25_ce0 = 1'b1;
    end else begin
        Xtile_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd25) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_25_we0 = 1'b1;
    end else begin
        Xtile_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_26_ce0 = 1'b1;
    end else begin
        Xtile_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd26) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_26_we0 = 1'b1;
    end else begin
        Xtile_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_27_ce0 = 1'b1;
    end else begin
        Xtile_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd27) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_27_we0 = 1'b1;
    end else begin
        Xtile_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_28_ce0 = 1'b1;
    end else begin
        Xtile_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd28) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_28_we0 = 1'b1;
    end else begin
        Xtile_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_29_ce0 = 1'b1;
    end else begin
        Xtile_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd29) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_29_we0 = 1'b1;
    end else begin
        Xtile_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_2_ce0 = 1'b1;
    end else begin
        Xtile_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_2_we0 = 1'b1;
    end else begin
        Xtile_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_30_ce0 = 1'b1;
    end else begin
        Xtile_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd30) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_30_we0 = 1'b1;
    end else begin
        Xtile_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_31_ce0 = 1'b1;
    end else begin
        Xtile_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd31) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_31_we0 = 1'b1;
    end else begin
        Xtile_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_3_ce0 = 1'b1;
    end else begin
        Xtile_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_3_we0 = 1'b1;
    end else begin
        Xtile_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_4_ce0 = 1'b1;
    end else begin
        Xtile_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_4_we0 = 1'b1;
    end else begin
        Xtile_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_5_ce0 = 1'b1;
    end else begin
        Xtile_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_5_we0 = 1'b1;
    end else begin
        Xtile_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_6_ce0 = 1'b1;
    end else begin
        Xtile_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_6_we0 = 1'b1;
    end else begin
        Xtile_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_7_ce0 = 1'b1;
    end else begin
        Xtile_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_7_we0 = 1'b1;
    end else begin
        Xtile_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_8_ce0 = 1'b1;
    end else begin
        Xtile_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_8_we0 = 1'b1;
    end else begin
        Xtile_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_9_ce0 = 1'b1;
    end else begin
        Xtile_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_9_we0 = 1'b1;
    end else begin
        Xtile_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_ce0 = 1'b1;
    end else begin
        Xtile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln62_reg_879 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Xtile_we0 = 1'b1;
    end else begin
        Xtile_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_687_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_188;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten77_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten77_load = indvar_flatten77_fu_192;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_kk_load = 6'd0;
    end else begin
        ap_sig_allocacmp_kk_load = kk_fu_184;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Xbuf_address0 = zext_ln64_2_fu_789_p1;

assign Xtile_10_address0 = zext_ln61_fu_815_p1;

assign Xtile_10_d0 = Xbuf_q0;

assign Xtile_11_address0 = zext_ln61_fu_815_p1;

assign Xtile_11_d0 = Xbuf_q0;

assign Xtile_12_address0 = zext_ln61_fu_815_p1;

assign Xtile_12_d0 = Xbuf_q0;

assign Xtile_13_address0 = zext_ln61_fu_815_p1;

assign Xtile_13_d0 = Xbuf_q0;

assign Xtile_14_address0 = zext_ln61_fu_815_p1;

assign Xtile_14_d0 = Xbuf_q0;

assign Xtile_15_address0 = zext_ln61_fu_815_p1;

assign Xtile_15_d0 = Xbuf_q0;

assign Xtile_16_address0 = zext_ln61_fu_815_p1;

assign Xtile_16_d0 = Xbuf_q0;

assign Xtile_17_address0 = zext_ln61_fu_815_p1;

assign Xtile_17_d0 = Xbuf_q0;

assign Xtile_18_address0 = zext_ln61_fu_815_p1;

assign Xtile_18_d0 = Xbuf_q0;

assign Xtile_19_address0 = zext_ln61_fu_815_p1;

assign Xtile_19_d0 = Xbuf_q0;

assign Xtile_1_address0 = zext_ln61_fu_815_p1;

assign Xtile_1_d0 = Xbuf_q0;

assign Xtile_20_address0 = zext_ln61_fu_815_p1;

assign Xtile_20_d0 = Xbuf_q0;

assign Xtile_21_address0 = zext_ln61_fu_815_p1;

assign Xtile_21_d0 = Xbuf_q0;

assign Xtile_22_address0 = zext_ln61_fu_815_p1;

assign Xtile_22_d0 = Xbuf_q0;

assign Xtile_23_address0 = zext_ln61_fu_815_p1;

assign Xtile_23_d0 = Xbuf_q0;

assign Xtile_24_address0 = zext_ln61_fu_815_p1;

assign Xtile_24_d0 = Xbuf_q0;

assign Xtile_25_address0 = zext_ln61_fu_815_p1;

assign Xtile_25_d0 = Xbuf_q0;

assign Xtile_26_address0 = zext_ln61_fu_815_p1;

assign Xtile_26_d0 = Xbuf_q0;

assign Xtile_27_address0 = zext_ln61_fu_815_p1;

assign Xtile_27_d0 = Xbuf_q0;

assign Xtile_28_address0 = zext_ln61_fu_815_p1;

assign Xtile_28_d0 = Xbuf_q0;

assign Xtile_29_address0 = zext_ln61_fu_815_p1;

assign Xtile_29_d0 = Xbuf_q0;

assign Xtile_2_address0 = zext_ln61_fu_815_p1;

assign Xtile_2_d0 = Xbuf_q0;

assign Xtile_30_address0 = zext_ln61_fu_815_p1;

assign Xtile_30_d0 = Xbuf_q0;

assign Xtile_31_address0 = zext_ln61_fu_815_p1;

assign Xtile_31_d0 = Xbuf_q0;

assign Xtile_3_address0 = zext_ln61_fu_815_p1;

assign Xtile_3_d0 = Xbuf_q0;

assign Xtile_4_address0 = zext_ln61_fu_815_p1;

assign Xtile_4_d0 = Xbuf_q0;

assign Xtile_5_address0 = zext_ln61_fu_815_p1;

assign Xtile_5_d0 = Xbuf_q0;

assign Xtile_6_address0 = zext_ln61_fu_815_p1;

assign Xtile_6_d0 = Xbuf_q0;

assign Xtile_7_address0 = zext_ln61_fu_815_p1;

assign Xtile_7_d0 = Xbuf_q0;

assign Xtile_8_address0 = zext_ln61_fu_815_p1;

assign Xtile_8_d0 = Xbuf_q0;

assign Xtile_9_address0 = zext_ln61_fu_815_p1;

assign Xtile_9_d0 = Xbuf_q0;

assign Xtile_address0 = zext_ln61_fu_815_p1;

assign Xtile_d0 = Xbuf_q0;

assign add_ln61_1_fu_733_p2 = (select_ln61_1_fu_725_p3 + trunc_ln37_mid2);

assign add_ln61_2_fu_693_p2 = (ap_sig_allocacmp_indvar_flatten77_load + 11'd1);

assign add_ln61_fu_705_p2 = (ap_sig_allocacmp_i_load + 6'd1);

assign add_ln62_fu_794_p2 = (select_ln61_fu_717_p3 + 6'd1);

assign add_ln64_1_fu_783_p2 = (sub_ln64_fu_759_p2 + zext_ln64_1_fu_779_p1);

assign add_ln64_fu_773_p2 = (zext_ln62_fu_765_p1 + k0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln61_fu_687_p2 = ((ap_sig_allocacmp_indvar_flatten77_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_711_p2 = ((ap_sig_allocacmp_kk_load == 6'd32) ? 1'b1 : 1'b0);

assign select_ln61_1_fu_725_p3 = ((icmp_ln62_fu_711_p2[0:0] == 1'b1) ? add_ln61_fu_705_p2 : ap_sig_allocacmp_i_load);

assign select_ln61_fu_717_p3 = ((icmp_ln62_fu_711_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_kk_load);

assign sub_ln64_fu_759_p2 = (tmp_7_fu_739_p3 - zext_ln64_fu_755_p1);

assign tmp_7_fu_739_p3 = {{add_ln61_1_fu_733_p2}, {10'd0}};

assign tmp_8_fu_747_p3 = {{add_ln61_1_fu_733_p2}, {8'd0}};

assign trunc_ln62_fu_769_p1 = select_ln61_fu_717_p3[4:0];

assign zext_ln61_fu_815_p1 = select_ln61_1_reg_874;

assign zext_ln62_fu_765_p1 = select_ln61_fu_717_p3;

assign zext_ln64_1_fu_779_p1 = add_ln64_fu_773_p2;

assign zext_ln64_2_fu_789_p1 = add_ln64_1_fu_783_p2;

assign zext_ln64_fu_755_p1 = tmp_8_fu_747_p3;

endmodule //gemm_int8_gemm_int8_Pipeline_load_Xtile_VITIS_LOOP_62_3
